/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttemptResponse,
  AttemptResponsePageResponse,
  CreateSqlQueryRequest,
  CreateSqlTaskRequest,
  CreateTopicRequest,
  GetAllAttemptsParams,
  GetAllSqlQueriesParams,
  GetAllSqlTasksParams,
  GetAllTopicsParams,
  HttpValidationProblemDetails,
  MoveTopicRequest,
  ProblemDetails,
  SqlQueryResponse,
  SqlQueryResponsePageResponse,
  SqlTaskResponse,
  SqlTaskResponsePageResponse,
  SubmitAttemptRequest,
  SubmitAttemptResponse,
  TeacherTaskDetailsResponse,
  TopicResponse,
  TopicResponsePageResponse,
  UpdateSqlQueryRequest,
  UpdateSqlTaskRequest,
  UpdateTopicRequest
} from '../model';

import { sqlmoduleFetch } from '../../../shared/http/sqlmodule-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type createTopicResponse201 = {
  data: TopicResponse
  status: 201
}

export type createTopicResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createTopicResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createTopicResponseSuccess = (createTopicResponse201) & {
  headers: Headers;
};
export type createTopicResponseError = (createTopicResponse400 | createTopicResponse409) & {
  headers: Headers;
};

export type createTopicResponse = (createTopicResponseSuccess | createTopicResponseError)

export const getCreateTopicUrl = () => {




  return `/api/v1/topics`
}

/**
 * Создаёт новую тему тренажёра. Возвращает 201 Created с телом ответа. ParentTopicId = null — корневая тема. 400 — не прошла валидация. 409 — родительская тема с указанным ParentTopicId не найдена.
 * @summary Создать тему
 */
export const createTopic = async (createTopicRequest: CreateTopicRequest, options?: RequestInit): Promise<createTopicResponse> => {

  return sqlmoduleFetch<createTopicResponse>(getCreateTopicUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTopicRequest)
  }
);}





export const getCreateTopicMutationOptions = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTopic>>, TError,{data: CreateTopicRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createTopic>>, TError,{data: CreateTopicRequest}, TContext> => {

const mutationKey = ['createTopic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTopic>>, {data: CreateTopicRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTopic(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTopicMutationResult = NonNullable<Awaited<ReturnType<typeof createTopic>>>
    export type CreateTopicMutationBody = CreateTopicRequest
    export type CreateTopicMutationError = HttpValidationProblemDetails | ProblemDetails

    /**
 * @summary Создать тему
 */
export const useCreateTopic = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTopic>>, TError,{data: CreateTopicRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTopic>>,
        TError,
        {data: CreateTopicRequest},
        TContext
      > => {
      return useMutation(getCreateTopicMutationOptions(options), queryClient);
    }
    export type getAllTopicsResponse200 = {
  data: TopicResponsePageResponse
  status: 200
}

export type getAllTopicsResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getAllTopicsResponseSuccess = (getAllTopicsResponse200) & {
  headers: Headers;
};
export type getAllTopicsResponseError = (getAllTopicsResponse400) & {
  headers: Headers;
};

export type getAllTopicsResponse = (getAllTopicsResponseSuccess | getAllTopicsResponseError)

export const getGetAllTopicsUrl = (params?: GetAllTopicsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/topics?${stringifiedParams}` : `/api/v1/topics`
}

/**
 * Возвращает 200 OK со страницей тем, отсортированных по названию. offset — количество пропускаемых записей (>= 0, по умолчанию 0). limit — размер страницы (1–100, по умолчанию 20). 400 — невалидные параметры пагинации.
 * @summary Список тем с пагинацией
 */
export const getAllTopics = async (params?: GetAllTopicsParams, options?: RequestInit): Promise<getAllTopicsResponse> => {

  return sqlmoduleFetch<getAllTopicsResponse>(getGetAllTopicsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllTopicsQueryKey = (params?: GetAllTopicsParams,) => {
    return [
    `/api/v1/topics`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllTopicsQueryOptions = <TData = Awaited<ReturnType<typeof getAllTopics>>, TError = HttpValidationProblemDetails>(params?: GetAllTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTopics>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllTopicsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllTopics>>> = ({ signal }) => getAllTopics(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllTopics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllTopicsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllTopics>>>
export type GetAllTopicsQueryError = HttpValidationProblemDetails


export function useGetAllTopics<TData = Awaited<ReturnType<typeof getAllTopics>>, TError = HttpValidationProblemDetails>(
 params: undefined |  GetAllTopicsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTopics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTopics>>,
          TError,
          Awaited<ReturnType<typeof getAllTopics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTopics<TData = Awaited<ReturnType<typeof getAllTopics>>, TError = HttpValidationProblemDetails>(
 params?: GetAllTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTopics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllTopics>>,
          TError,
          Awaited<ReturnType<typeof getAllTopics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllTopics<TData = Awaited<ReturnType<typeof getAllTopics>>, TError = HttpValidationProblemDetails>(
 params?: GetAllTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTopics>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Список тем с пагинацией
 */

export function useGetAllTopics<TData = Awaited<ReturnType<typeof getAllTopics>>, TError = HttpValidationProblemDetails>(
 params?: GetAllTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllTopics>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllTopicsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteTopicResponse204 = {
  data: void
  status: 204
}

export type deleteTopicResponse404 = {
  data: ProblemDetails
  status: 404
}

export type deleteTopicResponse409 = {
  data: ProblemDetails
  status: 409
}

export type deleteTopicResponseSuccess = (deleteTopicResponse204) & {
  headers: Headers;
};
export type deleteTopicResponseError = (deleteTopicResponse404 | deleteTopicResponse409) & {
  headers: Headers;
};

export type deleteTopicResponse = (deleteTopicResponseSuccess | deleteTopicResponseError)

export const getDeleteTopicUrl = (id: string,) => {




  return `/api/v1/topics/${id}`
}

/**
 * Удаляет тему по Id. Возвращает 204 No Content. 404 — тема не найдена. 409 — тема содержит подтемы или задания.
 * @summary Удалить тему
 */
export const deleteTopic = async (id: string, options?: RequestInit): Promise<deleteTopicResponse> => {

  return sqlmoduleFetch<deleteTopicResponse>(getDeleteTopicUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteTopicMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTopic>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTopic>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteTopic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTopic>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteTopic(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTopicMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTopic>>>

    export type DeleteTopicMutationError = ProblemDetails

    /**
 * @summary Удалить тему
 */
export const useDeleteTopic = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTopic>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTopic>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteTopicMutationOptions(options), queryClient);
    }
    export type getTopicByIdResponse200 = {
  data: TopicResponse
  status: 200
}

export type getTopicByIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getTopicByIdResponseSuccess = (getTopicByIdResponse200) & {
  headers: Headers;
};
export type getTopicByIdResponseError = (getTopicByIdResponse404) & {
  headers: Headers;
};

export type getTopicByIdResponse = (getTopicByIdResponseSuccess | getTopicByIdResponseError)

export const getGetTopicByIdUrl = (id: string,) => {




  return `/api/v1/topics/${id}`
}

/**
 * Возвращает 200 OK с данными темы. 404 — тема с указанным id не найдена.
 * @summary Получить тему по Id
 */
export const getTopicById = async (id: string, options?: RequestInit): Promise<getTopicByIdResponse> => {

  return sqlmoduleFetch<getTopicByIdResponse>(getGetTopicByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTopicByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/topics/${id}`
    ] as const;
    }


export const getGetTopicByIdQueryOptions = <TData = Awaited<ReturnType<typeof getTopicById>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopicByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopicById>>> = ({ signal }) => getTopicById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopicById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTopicByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTopicById>>>
export type GetTopicByIdQueryError = ProblemDetails


export function useGetTopicById<TData = Awaited<ReturnType<typeof getTopicById>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicById>>,
          TError,
          Awaited<ReturnType<typeof getTopicById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopicById<TData = Awaited<ReturnType<typeof getTopicById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTopicById>>,
          TError,
          Awaited<ReturnType<typeof getTopicById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTopicById<TData = Awaited<ReturnType<typeof getTopicById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить тему по Id
 */

export function useGetTopicById<TData = Awaited<ReturnType<typeof getTopicById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTopicById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTopicByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateTopicResponse204 = {
  data: void
  status: 204
}

export type updateTopicResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateTopicResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateTopicResponseSuccess = (updateTopicResponse204) & {
  headers: Headers;
};
export type updateTopicResponseError = (updateTopicResponse400 | updateTopicResponse404) & {
  headers: Headers;
};

export type updateTopicResponse = (updateTopicResponseSuccess | updateTopicResponseError)

export const getUpdateTopicUrl = (id: string,) => {




  return `/api/v1/topics/${id}`
}

/**
 * Обновляет название существующей темы. Возвращает 204 No Content. 400 — не прошла валидация. 404 — тема с указанным id не найдена.
 * @summary Обновить тему
 */
export const updateTopic = async (id: string,
    updateTopicRequest: UpdateTopicRequest, options?: RequestInit): Promise<updateTopicResponse> => {

  return sqlmoduleFetch<updateTopicResponse>(getUpdateTopicUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateTopicRequest)
  }
);}





export const getUpdateTopicMutationOptions = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTopic>>, TError,{id: string;data: UpdateTopicRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTopic>>, TError,{id: string;data: UpdateTopicRequest}, TContext> => {

const mutationKey = ['updateTopic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTopic>>, {id: string;data: UpdateTopicRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTopic(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTopicMutationResult = NonNullable<Awaited<ReturnType<typeof updateTopic>>>
    export type UpdateTopicMutationBody = UpdateTopicRequest
    export type UpdateTopicMutationError = HttpValidationProblemDetails | ProblemDetails

    /**
 * @summary Обновить тему
 */
export const useUpdateTopic = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTopic>>, TError,{id: string;data: UpdateTopicRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTopic>>,
        TError,
        {id: string;data: UpdateTopicRequest},
        TContext
      > => {
      return useMutation(getUpdateTopicMutationOptions(options), queryClient);
    }
    export type moveTopicResponse204 = {
  data: void
  status: 204
}

export type moveTopicResponse404 = {
  data: ProblemDetails
  status: 404
}

export type moveTopicResponse409 = {
  data: ProblemDetails
  status: 409
}

export type moveTopicResponseSuccess = (moveTopicResponse204) & {
  headers: Headers;
};
export type moveTopicResponseError = (moveTopicResponse404 | moveTopicResponse409) & {
  headers: Headers;
};

export type moveTopicResponse = (moveTopicResponseSuccess | moveTopicResponseError)

export const getMoveTopicUrl = (id: string,) => {




  return `/api/v1/topics/${id}/parent`
}

/**
 * Перемещает тему в иерархии. Возвращает 204 No Content. 404 — тема с указанным id не найдена. 409 — новый родитель не найден или перемещение создаёт цикл.
 * @summary Переместить тему
 */
export const moveTopic = async (id: string,
    moveTopicRequest: MoveTopicRequest, options?: RequestInit): Promise<moveTopicResponse> => {

  return sqlmoduleFetch<moveTopicResponse>(getMoveTopicUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(moveTopicRequest)
  }
);}





export const getMoveTopicMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveTopic>>, TError,{id: string;data: MoveTopicRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof moveTopic>>, TError,{id: string;data: MoveTopicRequest}, TContext> => {

const mutationKey = ['moveTopic'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveTopic>>, {id: string;data: MoveTopicRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  moveTopic(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MoveTopicMutationResult = NonNullable<Awaited<ReturnType<typeof moveTopic>>>
    export type MoveTopicMutationBody = MoveTopicRequest
    export type MoveTopicMutationError = ProblemDetails

    /**
 * @summary Переместить тему
 */
export const useMoveTopic = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof moveTopic>>, TError,{id: string;data: MoveTopicRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof moveTopic>>,
        TError,
        {id: string;data: MoveTopicRequest},
        TContext
      > => {
      return useMutation(getMoveTopicMutationOptions(options), queryClient);
    }
    export type createSqlTaskResponse201 = {
  data: SqlTaskResponse
  status: 201
}

export type createSqlTaskResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createSqlTaskResponse409 = {
  data: ProblemDetails
  status: 409
}

export type createSqlTaskResponse422 = {
  data: ProblemDetails
  status: 422
}

export type createSqlTaskResponseSuccess = (createSqlTaskResponse201) & {
  headers: Headers;
};
export type createSqlTaskResponseError = (createSqlTaskResponse400 | createSqlTaskResponse409 | createSqlTaskResponse422) & {
  headers: Headers;
};

export type createSqlTaskResponse = (createSqlTaskResponseSuccess | createSqlTaskResponseError)

export const getCreateSqlTaskUrl = () => {




  return `/api/v1/sql-tasks`
}

/**
 * Создаёт новое задание тренажёра в статусе Draft. Для публикации используйте отдельную операцию. Возвращает 201 Created с телом ответа. 422 — не прошла бизнес-валидация. 409 — TargetDb, тема или SQL-запрос не найдены.
 * @summary Создать SQL-задание
 */
export const createSqlTask = async (createSqlTaskRequest: CreateSqlTaskRequest, options?: RequestInit): Promise<createSqlTaskResponse> => {

  return sqlmoduleFetch<createSqlTaskResponse>(getCreateSqlTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSqlTaskRequest)
  }
);}





export const getCreateSqlTaskMutationOptions = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSqlTask>>, TError,{data: CreateSqlTaskRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createSqlTask>>, TError,{data: CreateSqlTaskRequest}, TContext> => {

const mutationKey = ['createSqlTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSqlTask>>, {data: CreateSqlTaskRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSqlTask(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSqlTaskMutationResult = NonNullable<Awaited<ReturnType<typeof createSqlTask>>>
    export type CreateSqlTaskMutationBody = CreateSqlTaskRequest
    export type CreateSqlTaskMutationError = HttpValidationProblemDetails | ProblemDetails

    /**
 * @summary Создать SQL-задание
 */
export const useCreateSqlTask = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSqlTask>>, TError,{data: CreateSqlTaskRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSqlTask>>,
        TError,
        {data: CreateSqlTaskRequest},
        TContext
      > => {
      return useMutation(getCreateSqlTaskMutationOptions(options), queryClient);
    }
    export type getAllSqlTasksResponse200 = {
  data: SqlTaskResponsePageResponse
  status: 200
}

export type getAllSqlTasksResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getAllSqlTasksResponseSuccess = (getAllSqlTasksResponse200) & {
  headers: Headers;
};
export type getAllSqlTasksResponseError = (getAllSqlTasksResponse400) & {
  headers: Headers;
};

export type getAllSqlTasksResponse = (getAllSqlTasksResponseSuccess | getAllSqlTasksResponseError)

export const getGetAllSqlTasksUrl = (params?: GetAllSqlTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sql-tasks?${stringifiedParams}` : `/api/v1/sql-tasks`
}

/**
 * Возвращает 200 OK со страницей заданий, отсортированных по сложности, затем по названию. offset — количество пропускаемых записей (>= 0, по умолчанию 0). limit — размер страницы (1–100, по умолчанию 20). 400 — невалидные параметры пагинации.
 * @summary Список SQL-заданий с пагинацией
 */
export const getAllSqlTasks = async (params?: GetAllSqlTasksParams, options?: RequestInit): Promise<getAllSqlTasksResponse> => {

  return sqlmoduleFetch<getAllSqlTasksResponse>(getGetAllSqlTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllSqlTasksQueryKey = (params?: GetAllSqlTasksParams,) => {
    return [
    `/api/v1/sql-tasks`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllSqlTasksQueryOptions = <TData = Awaited<ReturnType<typeof getAllSqlTasks>>, TError = HttpValidationProblemDetails>(params?: GetAllSqlTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlTasks>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSqlTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSqlTasks>>> = ({ signal }) => getAllSqlTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSqlTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllSqlTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSqlTasks>>>
export type GetAllSqlTasksQueryError = HttpValidationProblemDetails


export function useGetAllSqlTasks<TData = Awaited<ReturnType<typeof getAllSqlTasks>>, TError = HttpValidationProblemDetails>(
 params: undefined |  GetAllSqlTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSqlTasks>>,
          TError,
          Awaited<ReturnType<typeof getAllSqlTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllSqlTasks<TData = Awaited<ReturnType<typeof getAllSqlTasks>>, TError = HttpValidationProblemDetails>(
 params?: GetAllSqlTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSqlTasks>>,
          TError,
          Awaited<ReturnType<typeof getAllSqlTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllSqlTasks<TData = Awaited<ReturnType<typeof getAllSqlTasks>>, TError = HttpValidationProblemDetails>(
 params?: GetAllSqlTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlTasks>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Список SQL-заданий с пагинацией
 */

export function useGetAllSqlTasks<TData = Awaited<ReturnType<typeof getAllSqlTasks>>, TError = HttpValidationProblemDetails>(
 params?: GetAllSqlTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlTasks>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllSqlTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteSqlTaskResponse204 = {
  data: void
  status: 204
}

export type deleteSqlTaskResponse404 = {
  data: ProblemDetails
  status: 404
}

export type deleteSqlTaskResponse409 = {
  data: ProblemDetails
  status: 409
}

export type deleteSqlTaskResponseSuccess = (deleteSqlTaskResponse204) & {
  headers: Headers;
};
export type deleteSqlTaskResponseError = (deleteSqlTaskResponse404 | deleteSqlTaskResponse409) & {
  headers: Headers;
};

export type deleteSqlTaskResponse = (deleteSqlTaskResponseSuccess | deleteSqlTaskResponseError)

export const getDeleteSqlTaskUrl = (id: string,) => {




  return `/api/v1/sql-tasks/${id}`
}

/**
 * Удаляет задание по Id. Возвращает 204 No Content. 404 — задание не найдено. 409 — задание имеет попытки выполнения.
 * @summary Удалить SQL-задание
 */
export const deleteSqlTask = async (id: string, options?: RequestInit): Promise<deleteSqlTaskResponse> => {

  return sqlmoduleFetch<deleteSqlTaskResponse>(getDeleteSqlTaskUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteSqlTaskMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSqlTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSqlTask>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSqlTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSqlTask>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSqlTask(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSqlTaskMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSqlTask>>>

    export type DeleteSqlTaskMutationError = ProblemDetails

    /**
 * @summary Удалить SQL-задание
 */
export const useDeleteSqlTask = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSqlTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSqlTask>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteSqlTaskMutationOptions(options), queryClient);
    }
    export type getSqlTaskByIdResponse200 = {
  data: SqlTaskResponse
  status: 200
}

export type getSqlTaskByIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getSqlTaskByIdResponseSuccess = (getSqlTaskByIdResponse200) & {
  headers: Headers;
};
export type getSqlTaskByIdResponseError = (getSqlTaskByIdResponse404) & {
  headers: Headers;
};

export type getSqlTaskByIdResponse = (getSqlTaskByIdResponseSuccess | getSqlTaskByIdResponseError)

export const getGetSqlTaskByIdUrl = (id: string,) => {




  return `/api/v1/sql-tasks/${id}`
}

/**
 * Возвращает 200 OK с данными задания. 404 — задание с указанным id не найдено.
 * @summary Получить SQL-задание по Id
 */
export const getSqlTaskById = async (id: string, options?: RequestInit): Promise<getSqlTaskByIdResponse> => {

  return sqlmoduleFetch<getSqlTaskByIdResponse>(getGetSqlTaskByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSqlTaskByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/sql-tasks/${id}`
    ] as const;
    }


export const getGetSqlTaskByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSqlTaskById>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlTaskById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSqlTaskByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSqlTaskById>>> = ({ signal }) => getSqlTaskById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSqlTaskById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSqlTaskByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSqlTaskById>>>
export type GetSqlTaskByIdQueryError = ProblemDetails


export function useGetSqlTaskById<TData = Awaited<ReturnType<typeof getSqlTaskById>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlTaskById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSqlTaskById>>,
          TError,
          Awaited<ReturnType<typeof getSqlTaskById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSqlTaskById<TData = Awaited<ReturnType<typeof getSqlTaskById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlTaskById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSqlTaskById>>,
          TError,
          Awaited<ReturnType<typeof getSqlTaskById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSqlTaskById<TData = Awaited<ReturnType<typeof getSqlTaskById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlTaskById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить SQL-задание по Id
 */

export function useGetSqlTaskById<TData = Awaited<ReturnType<typeof getSqlTaskById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlTaskById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSqlTaskByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateSqlTaskResponse204 = {
  data: void
  status: 204
}

export type updateSqlTaskResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateSqlTaskResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateSqlTaskResponse409 = {
  data: ProblemDetails
  status: 409
}

export type updateSqlTaskResponseSuccess = (updateSqlTaskResponse204) & {
  headers: Headers;
};
export type updateSqlTaskResponseError = (updateSqlTaskResponse400 | updateSqlTaskResponse404 | updateSqlTaskResponse409) & {
  headers: Headers;
};

export type updateSqlTaskResponse = (updateSqlTaskResponseSuccess | updateSqlTaskResponseError)

export const getUpdateSqlTaskUrl = (id: string,) => {




  return `/api/v1/sql-tasks/${id}`
}

/**
 * Обновляет название, текст, сложность и статус, кроме перехода в Published (FK не меняются). Для публикации используйте отдельную операцию. Возвращает 204 No Content. 400 — не прошла валидация. 404 — задание с указанным id не найдено. 409 — предпринята публикация через обычное обновление.
 * @summary Обновить SQL-задание
 */
export const updateSqlTask = async (id: string,
    updateSqlTaskRequest: UpdateSqlTaskRequest, options?: RequestInit): Promise<updateSqlTaskResponse> => {

  return sqlmoduleFetch<updateSqlTaskResponse>(getUpdateSqlTaskUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSqlTaskRequest)
  }
);}





export const getUpdateSqlTaskMutationOptions = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSqlTask>>, TError,{id: string;data: UpdateSqlTaskRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSqlTask>>, TError,{id: string;data: UpdateSqlTaskRequest}, TContext> => {

const mutationKey = ['updateSqlTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSqlTask>>, {id: string;data: UpdateSqlTaskRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSqlTask(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSqlTaskMutationResult = NonNullable<Awaited<ReturnType<typeof updateSqlTask>>>
    export type UpdateSqlTaskMutationBody = UpdateSqlTaskRequest
    export type UpdateSqlTaskMutationError = HttpValidationProblemDetails | ProblemDetails

    /**
 * @summary Обновить SQL-задание
 */
export const useUpdateSqlTask = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSqlTask>>, TError,{id: string;data: UpdateSqlTaskRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSqlTask>>,
        TError,
        {id: string;data: UpdateSqlTaskRequest},
        TContext
      > => {
      return useMutation(getUpdateSqlTaskMutationOptions(options), queryClient);
    }
    export type publishSqlTaskResponse200 = {
  data: SqlTaskResponse
  status: 200
}

export type publishSqlTaskResponse404 = {
  data: ProblemDetails
  status: 404
}

export type publishSqlTaskResponse409 = {
  data: ProblemDetails
  status: 409
}

export type publishSqlTaskResponse422 = {
  data: ProblemDetails
  status: 422
}

export type publishSqlTaskResponseSuccess = (publishSqlTaskResponse200) & {
  headers: Headers;
};
export type publishSqlTaskResponseError = (publishSqlTaskResponse404 | publishSqlTaskResponse409 | publishSqlTaskResponse422) & {
  headers: Headers;
};

export type publishSqlTaskResponse = (publishSqlTaskResponseSuccess | publishSqlTaskResponseError)

export const getPublishSqlTaskUrl = (id: string,) => {




  return `/api/v1/sql-tasks/${id}/publish`
}

/**
 * Публикует подготовленное Draft-задание. Эталонный запрос должен иметь проверенный результат, учебная база должна существовать, а у задания не должно быть попыток. Возвращает 200 OK с обновлённым заданием.
 * @summary Опубликовать SQL-задание
 */
export const publishSqlTask = async (id: string, options?: RequestInit): Promise<publishSqlTaskResponse> => {

  return sqlmoduleFetch<publishSqlTaskResponse>(getPublishSqlTaskUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPublishSqlTaskMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishSqlTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof publishSqlTask>>, TError,{id: string}, TContext> => {

const mutationKey = ['publishSqlTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishSqlTask>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  publishSqlTask(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishSqlTaskMutationResult = NonNullable<Awaited<ReturnType<typeof publishSqlTask>>>

    export type PublishSqlTaskMutationError = ProblemDetails

    /**
 * @summary Опубликовать SQL-задание
 */
export const usePublishSqlTask = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishSqlTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishSqlTask>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPublishSqlTaskMutationOptions(options), queryClient);
    }
    export type getTeacherTaskDetailsResponse200 = {
  data: TeacherTaskDetailsResponse
  status: 200
}

export type getTeacherTaskDetailsResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getTeacherTaskDetailsResponseSuccess = (getTeacherTaskDetailsResponse200) & {
  headers: Headers;
};
export type getTeacherTaskDetailsResponseError = (getTeacherTaskDetailsResponse404) & {
  headers: Headers;
};

export type getTeacherTaskDetailsResponse = (getTeacherTaskDetailsResponseSuccess | getTeacherTaskDetailsResponseError)

export const getGetTeacherTaskDetailsUrl = (taskId: string,) => {




  return `/api/v1/teacher/tasks/${taskId}/details`
}

/**
 * Возвращает задание, тему, эталонный запрос, учебную базу, состав таблиц, общее число попыток и пять последних попыток.
 * @summary Получить агрегированные детали задания для преподавателя
 */
export const getTeacherTaskDetails = async (taskId: string, options?: RequestInit): Promise<getTeacherTaskDetailsResponse> => {

  return sqlmoduleFetch<getTeacherTaskDetailsResponse>(getGetTeacherTaskDetailsUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTeacherTaskDetailsQueryKey = (taskId: string,) => {
    return [
    `/api/v1/teacher/tasks/${taskId}/details`
    ] as const;
    }


export const getGetTeacherTaskDetailsQueryOptions = <TData = Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError = ProblemDetails>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTeacherTaskDetailsQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTeacherTaskDetails>>> = ({ signal }) => getTeacherTaskDetails(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTeacherTaskDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof getTeacherTaskDetails>>>
export type GetTeacherTaskDetailsQueryError = ProblemDetails


export function useGetTeacherTaskDetails<TData = Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError = ProblemDetails>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherTaskDetails>>,
          TError,
          Awaited<ReturnType<typeof getTeacherTaskDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherTaskDetails<TData = Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTeacherTaskDetails>>,
          TError,
          Awaited<ReturnType<typeof getTeacherTaskDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTeacherTaskDetails<TData = Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить агрегированные детали задания для преподавателя
 */

export function useGetTeacherTaskDetails<TData = Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTeacherTaskDetails>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTeacherTaskDetailsQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createSqlQueryResponse201 = {
  data: SqlQueryResponse
  status: 201
}

export type createSqlQueryResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type createSqlQueryResponseSuccess = (createSqlQueryResponse201) & {
  headers: Headers;
};
export type createSqlQueryResponseError = (createSqlQueryResponse400) & {
  headers: Headers;
};

export type createSqlQueryResponse = (createSqlQueryResponseSuccess | createSqlQueryResponseError)

export const getCreateSqlQueryUrl = () => {




  return `/api/v1/sql-queries`
}

/**
 * Создаёт новый эталонный SQL-запрос. Возвращает 201 Created с телом ответа. 400 — не прошла валидация (пустой QueryText).
 * @summary Создать эталонный SQL-запрос
 */
export const createSqlQuery = async (createSqlQueryRequest: CreateSqlQueryRequest, options?: RequestInit): Promise<createSqlQueryResponse> => {

  return sqlmoduleFetch<createSqlQueryResponse>(getCreateSqlQueryUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSqlQueryRequest)
  }
);}





export const getCreateSqlQueryMutationOptions = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSqlQuery>>, TError,{data: CreateSqlQueryRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createSqlQuery>>, TError,{data: CreateSqlQueryRequest}, TContext> => {

const mutationKey = ['createSqlQuery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSqlQuery>>, {data: CreateSqlQueryRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSqlQuery(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSqlQueryMutationResult = NonNullable<Awaited<ReturnType<typeof createSqlQuery>>>
    export type CreateSqlQueryMutationBody = CreateSqlQueryRequest
    export type CreateSqlQueryMutationError = HttpValidationProblemDetails

    /**
 * @summary Создать эталонный SQL-запрос
 */
export const useCreateSqlQuery = <TError = HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSqlQuery>>, TError,{data: CreateSqlQueryRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSqlQuery>>,
        TError,
        {data: CreateSqlQueryRequest},
        TContext
      > => {
      return useMutation(getCreateSqlQueryMutationOptions(options), queryClient);
    }
    export type getAllSqlQueriesResponse200 = {
  data: SqlQueryResponsePageResponse
  status: 200
}

export type getAllSqlQueriesResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getAllSqlQueriesResponseSuccess = (getAllSqlQueriesResponse200) & {
  headers: Headers;
};
export type getAllSqlQueriesResponseError = (getAllSqlQueriesResponse400) & {
  headers: Headers;
};

export type getAllSqlQueriesResponse = (getAllSqlQueriesResponseSuccess | getAllSqlQueriesResponseError)

export const getGetAllSqlQueriesUrl = (params?: GetAllSqlQueriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/sql-queries?${stringifiedParams}` : `/api/v1/sql-queries`
}

/**
 * Возвращает 200 OK со страницей запросов, отсортированных по дате создания. offset — количество пропускаемых записей (>= 0, по умолчанию 0). limit — размер страницы (1–100, по умолчанию 20). 400 — невалидные параметры пагинации.
 * @summary Список SQL-запросов с пагинацией
 */
export const getAllSqlQueries = async (params?: GetAllSqlQueriesParams, options?: RequestInit): Promise<getAllSqlQueriesResponse> => {

  return sqlmoduleFetch<getAllSqlQueriesResponse>(getGetAllSqlQueriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllSqlQueriesQueryKey = (params?: GetAllSqlQueriesParams,) => {
    return [
    `/api/v1/sql-queries`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllSqlQueriesQueryOptions = <TData = Awaited<ReturnType<typeof getAllSqlQueries>>, TError = HttpValidationProblemDetails>(params?: GetAllSqlQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlQueries>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSqlQueriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSqlQueries>>> = ({ signal }) => getAllSqlQueries(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSqlQueries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllSqlQueriesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSqlQueries>>>
export type GetAllSqlQueriesQueryError = HttpValidationProblemDetails


export function useGetAllSqlQueries<TData = Awaited<ReturnType<typeof getAllSqlQueries>>, TError = HttpValidationProblemDetails>(
 params: undefined |  GetAllSqlQueriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlQueries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSqlQueries>>,
          TError,
          Awaited<ReturnType<typeof getAllSqlQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllSqlQueries<TData = Awaited<ReturnType<typeof getAllSqlQueries>>, TError = HttpValidationProblemDetails>(
 params?: GetAllSqlQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlQueries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllSqlQueries>>,
          TError,
          Awaited<ReturnType<typeof getAllSqlQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllSqlQueries<TData = Awaited<ReturnType<typeof getAllSqlQueries>>, TError = HttpValidationProblemDetails>(
 params?: GetAllSqlQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlQueries>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Список SQL-запросов с пагинацией
 */

export function useGetAllSqlQueries<TData = Awaited<ReturnType<typeof getAllSqlQueries>>, TError = HttpValidationProblemDetails>(
 params?: GetAllSqlQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllSqlQueries>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllSqlQueriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteSqlQueryResponse204 = {
  data: void
  status: 204
}

export type deleteSqlQueryResponse404 = {
  data: ProblemDetails
  status: 404
}

export type deleteSqlQueryResponse409 = {
  data: ProblemDetails
  status: 409
}

export type deleteSqlQueryResponseSuccess = (deleteSqlQueryResponse204) & {
  headers: Headers;
};
export type deleteSqlQueryResponseError = (deleteSqlQueryResponse404 | deleteSqlQueryResponse409) & {
  headers: Headers;
};

export type deleteSqlQueryResponse = (deleteSqlQueryResponseSuccess | deleteSqlQueryResponseError)

export const getDeleteSqlQueryUrl = (id: string,) => {




  return `/api/v1/sql-queries/${id}`
}

/**
 * Удаляет SQL-запрос по Id. Возвращает 204 No Content. 404 — запрос не найден. 409 — запрос используется заданиями или попытками.
 * @summary Удалить SQL-запрос
 */
export const deleteSqlQuery = async (id: string, options?: RequestInit): Promise<deleteSqlQueryResponse> => {

  return sqlmoduleFetch<deleteSqlQueryResponse>(getDeleteSqlQueryUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteSqlQueryMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSqlQuery>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSqlQuery>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSqlQuery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSqlQuery>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSqlQuery(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSqlQueryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSqlQuery>>>

    export type DeleteSqlQueryMutationError = ProblemDetails

    /**
 * @summary Удалить SQL-запрос
 */
export const useDeleteSqlQuery = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSqlQuery>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSqlQuery>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteSqlQueryMutationOptions(options), queryClient);
    }
    export type getSqlQueryByIdResponse200 = {
  data: SqlQueryResponse
  status: 200
}

export type getSqlQueryByIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getSqlQueryByIdResponseSuccess = (getSqlQueryByIdResponse200) & {
  headers: Headers;
};
export type getSqlQueryByIdResponseError = (getSqlQueryByIdResponse404) & {
  headers: Headers;
};

export type getSqlQueryByIdResponse = (getSqlQueryByIdResponseSuccess | getSqlQueryByIdResponseError)

export const getGetSqlQueryByIdUrl = (id: string,) => {




  return `/api/v1/sql-queries/${id}`
}

/**
 * Возвращает 200 OK с данными запроса. 404 — запрос с указанным id не найден.
 * @summary Получить SQL-запрос по Id
 */
export const getSqlQueryById = async (id: string, options?: RequestInit): Promise<getSqlQueryByIdResponse> => {

  return sqlmoduleFetch<getSqlQueryByIdResponse>(getGetSqlQueryByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSqlQueryByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/sql-queries/${id}`
    ] as const;
    }


export const getGetSqlQueryByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSqlQueryById>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlQueryById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSqlQueryByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSqlQueryById>>> = ({ signal }) => getSqlQueryById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSqlQueryById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSqlQueryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSqlQueryById>>>
export type GetSqlQueryByIdQueryError = ProblemDetails


export function useGetSqlQueryById<TData = Awaited<ReturnType<typeof getSqlQueryById>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlQueryById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSqlQueryById>>,
          TError,
          Awaited<ReturnType<typeof getSqlQueryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSqlQueryById<TData = Awaited<ReturnType<typeof getSqlQueryById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlQueryById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSqlQueryById>>,
          TError,
          Awaited<ReturnType<typeof getSqlQueryById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSqlQueryById<TData = Awaited<ReturnType<typeof getSqlQueryById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlQueryById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить SQL-запрос по Id
 */

export function useGetSqlQueryById<TData = Awaited<ReturnType<typeof getSqlQueryById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSqlQueryById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSqlQueryByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateSqlQueryResponse204 = {
  data: void
  status: 204
}

export type updateSqlQueryResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type updateSqlQueryResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateSqlQueryResponseSuccess = (updateSqlQueryResponse204) & {
  headers: Headers;
};
export type updateSqlQueryResponseError = (updateSqlQueryResponse400 | updateSqlQueryResponse404) & {
  headers: Headers;
};

export type updateSqlQueryResponse = (updateSqlQueryResponseSuccess | updateSqlQueryResponseError)

export const getUpdateSqlQueryUrl = (id: string,) => {




  return `/api/v1/sql-queries/${id}`
}

/**
 * Обновляет текст запроса и настройки сравнения. Возвращает 204 No Content. 400 — не прошла валидация. 404 — запрос с указанным id не найден.
 * @summary Обновить SQL-запрос
 */
export const updateSqlQuery = async (id: string,
    updateSqlQueryRequest: UpdateSqlQueryRequest, options?: RequestInit): Promise<updateSqlQueryResponse> => {

  return sqlmoduleFetch<updateSqlQueryResponse>(getUpdateSqlQueryUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSqlQueryRequest)
  }
);}





export const getUpdateSqlQueryMutationOptions = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSqlQuery>>, TError,{id: string;data: UpdateSqlQueryRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSqlQuery>>, TError,{id: string;data: UpdateSqlQueryRequest}, TContext> => {

const mutationKey = ['updateSqlQuery'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSqlQuery>>, {id: string;data: UpdateSqlQueryRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSqlQuery(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSqlQueryMutationResult = NonNullable<Awaited<ReturnType<typeof updateSqlQuery>>>
    export type UpdateSqlQueryMutationBody = UpdateSqlQueryRequest
    export type UpdateSqlQueryMutationError = HttpValidationProblemDetails | ProblemDetails

    /**
 * @summary Обновить SQL-запрос
 */
export const useUpdateSqlQuery = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSqlQuery>>, TError,{id: string;data: UpdateSqlQueryRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSqlQuery>>,
        TError,
        {id: string;data: UpdateSqlQueryRequest},
        TContext
      > => {
      return useMutation(getUpdateSqlQueryMutationOptions(options), queryClient);
    }
    export type deleteAttemptResponse204 = {
  data: void
  status: 204
}

export type deleteAttemptResponse404 = {
  data: ProblemDetails
  status: 404
}

export type deleteAttemptResponseSuccess = (deleteAttemptResponse204) & {
  headers: Headers;
};
export type deleteAttemptResponseError = (deleteAttemptResponse404) & {
  headers: Headers;
};

export type deleteAttemptResponse = (deleteAttemptResponseSuccess | deleteAttemptResponseError)

export const getDeleteAttemptUrl = (id: string,) => {




  return `/api/v1/attempts/${id}`
}

/**
 * Удаляет запись попытки по Id. Возвращает 204 No Content. 404 — попытка не найдена.
 * @summary Удалить попытку
 */
export const deleteAttempt = async (id: string, options?: RequestInit): Promise<deleteAttemptResponse> => {

  return sqlmoduleFetch<deleteAttemptResponse>(getDeleteAttemptUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAttemptMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttempt>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAttempt>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAttempt'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAttempt>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAttempt(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAttemptMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAttempt>>>

    export type DeleteAttemptMutationError = ProblemDetails

    /**
 * @summary Удалить попытку
 */
export const useDeleteAttempt = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttempt>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAttempt>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteAttemptMutationOptions(options), queryClient);
    }
    export type getAttemptByIdResponse200 = {
  data: AttemptResponse
  status: 200
}

export type getAttemptByIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getAttemptByIdResponseSuccess = (getAttemptByIdResponse200) & {
  headers: Headers;
};
export type getAttemptByIdResponseError = (getAttemptByIdResponse404) & {
  headers: Headers;
};

export type getAttemptByIdResponse = (getAttemptByIdResponseSuccess | getAttemptByIdResponseError)

export const getGetAttemptByIdUrl = (id: string,) => {




  return `/api/v1/attempts/${id}`
}

/**
 * Возвращает 200 OK с данными попытки. 404 — попытка с указанным id не найдена.
 * @summary Получить попытку по Id
 */
export const getAttemptById = async (id: string, options?: RequestInit): Promise<getAttemptByIdResponse> => {

  return sqlmoduleFetch<getAttemptByIdResponse>(getGetAttemptByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAttemptByIdQueryKey = (id: string,) => {
    return [
    `/api/v1/attempts/${id}`
    ] as const;
    }


export const getGetAttemptByIdQueryOptions = <TData = Awaited<ReturnType<typeof getAttemptById>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttemptById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttemptByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttemptById>>> = ({ signal }) => getAttemptById(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttemptById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttemptByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAttemptById>>>
export type GetAttemptByIdQueryError = ProblemDetails


export function useGetAttemptById<TData = Awaited<ReturnType<typeof getAttemptById>>, TError = ProblemDetails>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttemptById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttemptById>>,
          TError,
          Awaited<ReturnType<typeof getAttemptById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttemptById<TData = Awaited<ReturnType<typeof getAttemptById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttemptById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttemptById>>,
          TError,
          Awaited<ReturnType<typeof getAttemptById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttemptById<TData = Awaited<ReturnType<typeof getAttemptById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttemptById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить попытку по Id
 */

export function useGetAttemptById<TData = Awaited<ReturnType<typeof getAttemptById>>, TError = ProblemDetails>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttemptById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAttemptByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getAllAttemptsResponse200 = {
  data: AttemptResponsePageResponse
  status: 200
}

export type getAllAttemptsResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type getAllAttemptsResponseSuccess = (getAllAttemptsResponse200) & {
  headers: Headers;
};
export type getAllAttemptsResponseError = (getAllAttemptsResponse400) & {
  headers: Headers;
};

export type getAllAttemptsResponse = (getAllAttemptsResponseSuccess | getAllAttemptsResponseError)

export const getGetAllAttemptsUrl = (params?: GetAllAttemptsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/attempts?${stringifiedParams}` : `/api/v1/attempts`
}

/**
 * Возвращает 200 OK со страницей попыток, отсортированных по убыванию даты начала. offset — количество пропускаемых записей (>= 0, по умолчанию 0). limit — размер страницы (1–100, по умолчанию 20). taskId — необязательный фильтр по заданию. userId — необязательный фильтр по студенту. 400 — невалидные параметры пагинации.
 * @summary Список попыток с пагинацией
 */
export const getAllAttempts = async (params?: GetAllAttemptsParams, options?: RequestInit): Promise<getAllAttemptsResponse> => {

  return sqlmoduleFetch<getAllAttemptsResponse>(getGetAllAttemptsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllAttemptsQueryKey = (params?: GetAllAttemptsParams,) => {
    return [
    `/api/v1/attempts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllAttemptsQueryOptions = <TData = Awaited<ReturnType<typeof getAllAttempts>>, TError = HttpValidationProblemDetails>(params?: GetAllAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAttempts>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllAttemptsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllAttempts>>> = ({ signal }) => getAllAttempts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllAttempts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllAttemptsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllAttempts>>>
export type GetAllAttemptsQueryError = HttpValidationProblemDetails


export function useGetAllAttempts<TData = Awaited<ReturnType<typeof getAllAttempts>>, TError = HttpValidationProblemDetails>(
 params: undefined |  GetAllAttemptsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAttempts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAttempts>>,
          TError,
          Awaited<ReturnType<typeof getAllAttempts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAttempts<TData = Awaited<ReturnType<typeof getAllAttempts>>, TError = HttpValidationProblemDetails>(
 params?: GetAllAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAttempts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAttempts>>,
          TError,
          Awaited<ReturnType<typeof getAllAttempts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAttempts<TData = Awaited<ReturnType<typeof getAllAttempts>>, TError = HttpValidationProblemDetails>(
 params?: GetAllAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAttempts>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Список попыток с пагинацией
 */

export function useGetAllAttempts<TData = Awaited<ReturnType<typeof getAllAttempts>>, TError = HttpValidationProblemDetails>(
 params?: GetAllAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAttempts>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllAttemptsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type submitAttemptResponse201 = {
  data: SubmitAttemptResponse
  status: 201
}

export type submitAttemptResponse400 = {
  data: HttpValidationProblemDetails
  status: 400
}

export type submitAttemptResponse404 = {
  data: ProblemDetails
  status: 404
}

export type submitAttemptResponse409 = {
  data: ProblemDetails
  status: 409
}

export type submitAttemptResponseSuccess = (submitAttemptResponse201) & {
  headers: Headers;
};
export type submitAttemptResponseError = (submitAttemptResponse400 | submitAttemptResponse404 | submitAttemptResponse409) & {
  headers: Headers;
};

export type submitAttemptResponse = (submitAttemptResponseSuccess | submitAttemptResponseError)

export const getSubmitAttemptUrl = () => {




  return `/api/v1/attempts`
}

/**
 * Запускает SQL студента в песочнице, сравнивает с эталоном и сохраняет результат. UserId берётся из текущей сессии. Возвращает 201 Created с результатом проверки. 400 — не прошла валидация. 404 — задание не найдено. 409 — эталонный результат задания ещё не готов.
 * @summary Отправить попытку выполнения задания
 */
export const submitAttempt = async (submitAttemptRequest: SubmitAttemptRequest, options?: RequestInit): Promise<submitAttemptResponse> => {

  return sqlmoduleFetch<submitAttemptResponse>(getSubmitAttemptUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(submitAttemptRequest)
  }
);}





export const getSubmitAttemptMutationOptions = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitAttempt>>, TError,{data: SubmitAttemptRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof submitAttempt>>, TError,{data: SubmitAttemptRequest}, TContext> => {

const mutationKey = ['submitAttempt'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof submitAttempt>>, {data: SubmitAttemptRequest}> = (props) => {
          const {data} = props ?? {};

          return  submitAttempt(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SubmitAttemptMutationResult = NonNullable<Awaited<ReturnType<typeof submitAttempt>>>
    export type SubmitAttemptMutationBody = SubmitAttemptRequest
    export type SubmitAttemptMutationError = HttpValidationProblemDetails | ProblemDetails

    /**
 * @summary Отправить попытку выполнения задания
 */
export const useSubmitAttempt = <TError = HttpValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof submitAttempt>>, TError,{data: SubmitAttemptRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof submitAttempt>>,
        TError,
        {data: SubmitAttemptRequest},
        TContext
      > => {
      return useMutation(getSubmitAttemptMutationOptions(options), queryClient);
    }
