/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetStudentAttemptsParams,
  GetStudentTasksParams,
  GetStudentTopicsParams,
  HttpValidationProblemDetails,
  ProblemDetails,
  StudentAttemptListItemResponsePageResponse,
  StudentAttemptResponse,
  StudentTaskDetailsResponse,
  StudentTaskResponsePageResponse,
  StudentTaskSchemaResponse,
  StudentTopicResponsePageResponse
} from '../model';

import { sqlmoduleFetch } from '../../../shared/http/sqlmodule-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getStudentTopicsResponse200 = {
  data: StudentTopicResponsePageResponse
  status: 200
}

export type getStudentTopicsResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getStudentTopicsResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getStudentTopicsResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type getStudentTopicsResponseSuccess = (getStudentTopicsResponse200) & {
  headers: Headers;
};
export type getStudentTopicsResponseError = (getStudentTopicsResponse401 | getStudentTopicsResponse403 | getStudentTopicsResponse422) & {
  headers: Headers;
};

export type getStudentTopicsResponse = (getStudentTopicsResponseSuccess | getStudentTopicsResponseError)

export const getGetStudentTopicsUrl = (params?: GetStudentTopicsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/student/topics?${stringifiedParams}` : `/api/v1/student/topics`
}

export const getStudentTopics = async (params?: GetStudentTopicsParams, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getStudentTopicsResponse> => {

  return sqlmoduleFetch<getStudentTopicsResponse>(getGetStudentTopicsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentTopicsQueryKey = (params?: GetStudentTopicsParams,) => {
    return [
    `/api/v1/student/topics`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetStudentTopicsQueryOptions = <TData = Awaited<ReturnType<typeof getStudentTopics>>, TError = ProblemDetails | HttpValidationProblemDetails>(params?: GetStudentTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTopics>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentTopicsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentTopics>>> = ({ signal }) => getStudentTopics(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentTopics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentTopicsQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentTopics>>>
export type GetStudentTopicsQueryError = ProblemDetails | HttpValidationProblemDetails


export function useGetStudentTopics<TData = Awaited<ReturnType<typeof getStudentTopics>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params: undefined |  GetStudentTopicsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTopics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTopics>>,
          TError,
          Awaited<ReturnType<typeof getStudentTopics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTopics<TData = Awaited<ReturnType<typeof getStudentTopics>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTopics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTopics>>,
          TError,
          Awaited<ReturnType<typeof getStudentTopics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTopics<TData = Awaited<ReturnType<typeof getStudentTopics>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTopics>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStudentTopics<TData = Awaited<ReturnType<typeof getStudentTopics>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentTopicsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTopics>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentTopicsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getStudentTasksResponse200 = {
  data: StudentTaskResponsePageResponse
  status: 200
}

export type getStudentTasksResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getStudentTasksResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getStudentTasksResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type getStudentTasksResponseSuccess = (getStudentTasksResponse200) & {
  headers: Headers;
};
export type getStudentTasksResponseError = (getStudentTasksResponse401 | getStudentTasksResponse403 | getStudentTasksResponse422) & {
  headers: Headers;
};

export type getStudentTasksResponse = (getStudentTasksResponseSuccess | getStudentTasksResponseError)

export const getGetStudentTasksUrl = (params?: GetStudentTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/student/tasks?${stringifiedParams}` : `/api/v1/student/tasks`
}

export const getStudentTasks = async (params?: GetStudentTasksParams, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getStudentTasksResponse> => {

  return sqlmoduleFetch<getStudentTasksResponse>(getGetStudentTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentTasksQueryKey = (params?: GetStudentTasksParams,) => {
    return [
    `/api/v1/student/tasks`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetStudentTasksQueryOptions = <TData = Awaited<ReturnType<typeof getStudentTasks>>, TError = ProblemDetails | HttpValidationProblemDetails>(params?: GetStudentTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTasks>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentTasks>>> = ({ signal }) => getStudentTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentTasks>>>
export type GetStudentTasksQueryError = ProblemDetails | HttpValidationProblemDetails


export function useGetStudentTasks<TData = Awaited<ReturnType<typeof getStudentTasks>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params: undefined |  GetStudentTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTasks>>,
          TError,
          Awaited<ReturnType<typeof getStudentTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTasks<TData = Awaited<ReturnType<typeof getStudentTasks>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTasks>>,
          TError,
          Awaited<ReturnType<typeof getStudentTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTasks<TData = Awaited<ReturnType<typeof getStudentTasks>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTasks>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStudentTasks<TData = Awaited<ReturnType<typeof getStudentTasks>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTasks>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getStudentTaskByIdResponse200 = {
  data: StudentTaskDetailsResponse
  status: 200
}

export type getStudentTaskByIdResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getStudentTaskByIdResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getStudentTaskByIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getStudentTaskByIdResponseSuccess = (getStudentTaskByIdResponse200) & {
  headers: Headers;
};
export type getStudentTaskByIdResponseError = (getStudentTaskByIdResponse401 | getStudentTaskByIdResponse403 | getStudentTaskByIdResponse404) & {
  headers: Headers;
};

export type getStudentTaskByIdResponse = (getStudentTaskByIdResponseSuccess | getStudentTaskByIdResponseError)

export const getGetStudentTaskByIdUrl = (taskId: string,) => {




  return `/api/v1/student/tasks/${taskId}`
}

export const getStudentTaskById = async (taskId: string, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getStudentTaskByIdResponse> => {

  return sqlmoduleFetch<getStudentTaskByIdResponse>(getGetStudentTaskByIdUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentTaskByIdQueryKey = (taskId: string,) => {
    return [
    `/api/v1/student/tasks/${taskId}`
    ] as const;
    }


export const getGetStudentTaskByIdQueryOptions = <TData = Awaited<ReturnType<typeof getStudentTaskById>>, TError = ProblemDetails>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentTaskByIdQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentTaskById>>> = ({ signal }) => getStudentTaskById(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentTaskByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentTaskById>>>
export type GetStudentTaskByIdQueryError = ProblemDetails


export function useGetStudentTaskById<TData = Awaited<ReturnType<typeof getStudentTaskById>>, TError = ProblemDetails>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTaskById>>,
          TError,
          Awaited<ReturnType<typeof getStudentTaskById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTaskById<TData = Awaited<ReturnType<typeof getStudentTaskById>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTaskById>>,
          TError,
          Awaited<ReturnType<typeof getStudentTaskById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTaskById<TData = Awaited<ReturnType<typeof getStudentTaskById>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStudentTaskById<TData = Awaited<ReturnType<typeof getStudentTaskById>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentTaskByIdQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getStudentTaskSchemaResponse200 = {
  data: StudentTaskSchemaResponse
  status: 200
}

export type getStudentTaskSchemaResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getStudentTaskSchemaResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getStudentTaskSchemaResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getStudentTaskSchemaResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type getStudentTaskSchemaResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getStudentTaskSchemaResponseSuccess = (getStudentTaskSchemaResponse200) & {
  headers: Headers;
};
export type getStudentTaskSchemaResponseError = (getStudentTaskSchemaResponse401 | getStudentTaskSchemaResponse403 | getStudentTaskSchemaResponse404 | getStudentTaskSchemaResponse422 | getStudentTaskSchemaResponse500) & {
  headers: Headers;
};

export type getStudentTaskSchemaResponse = (getStudentTaskSchemaResponseSuccess | getStudentTaskSchemaResponseError)

export const getGetStudentTaskSchemaUrl = (taskId: string,) => {




  return `/api/v1/student/tasks/${taskId}/schema`
}

/**
 * Возвращает только структуру базы опубликованного задания: таблицы, колонки и внешние ключи. Закрытые задания скрываются ответом 404.
 * @summary Получить безопасную схему учебной базы задания
 */
export const getStudentTaskSchema = async (taskId: string, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getStudentTaskSchemaResponse> => {

  return sqlmoduleFetch<getStudentTaskSchemaResponse>(getGetStudentTaskSchemaUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentTaskSchemaQueryKey = (taskId: string,) => {
    return [
    `/api/v1/student/tasks/${taskId}/schema`
    ] as const;
    }


export const getGetStudentTaskSchemaQueryOptions = <TData = Awaited<ReturnType<typeof getStudentTaskSchema>>, TError = ProblemDetails | HttpValidationProblemDetails>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskSchema>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentTaskSchemaQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentTaskSchema>>> = ({ signal }) => getStudentTaskSchema(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskSchema>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentTaskSchemaQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentTaskSchema>>>
export type GetStudentTaskSchemaQueryError = ProblemDetails | HttpValidationProblemDetails


export function useGetStudentTaskSchema<TData = Awaited<ReturnType<typeof getStudentTaskSchema>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskSchema>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTaskSchema>>,
          TError,
          Awaited<ReturnType<typeof getStudentTaskSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTaskSchema<TData = Awaited<ReturnType<typeof getStudentTaskSchema>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskSchema>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentTaskSchema>>,
          TError,
          Awaited<ReturnType<typeof getStudentTaskSchema>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentTaskSchema<TData = Awaited<ReturnType<typeof getStudentTaskSchema>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskSchema>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить безопасную схему учебной базы задания
 */

export function useGetStudentTaskSchema<TData = Awaited<ReturnType<typeof getStudentTaskSchema>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentTaskSchema>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentTaskSchemaQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getStudentAttemptsResponse200 = {
  data: StudentAttemptListItemResponsePageResponse
  status: 200
}

export type getStudentAttemptsResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getStudentAttemptsResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getStudentAttemptsResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type getStudentAttemptsResponseSuccess = (getStudentAttemptsResponse200) & {
  headers: Headers;
};
export type getStudentAttemptsResponseError = (getStudentAttemptsResponse401 | getStudentAttemptsResponse403 | getStudentAttemptsResponse422) & {
  headers: Headers;
};

export type getStudentAttemptsResponse = (getStudentAttemptsResponseSuccess | getStudentAttemptsResponseError)

export const getGetStudentAttemptsUrl = (params?: GetStudentAttemptsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/student/attempts?${stringifiedParams}` : `/api/v1/student/attempts`
}

export const getStudentAttempts = async (params?: GetStudentAttemptsParams, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getStudentAttemptsResponse> => {

  return sqlmoduleFetch<getStudentAttemptsResponse>(getGetStudentAttemptsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentAttemptsQueryKey = (params?: GetStudentAttemptsParams,) => {
    return [
    `/api/v1/student/attempts`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetStudentAttemptsQueryOptions = <TData = Awaited<ReturnType<typeof getStudentAttempts>>, TError = ProblemDetails | HttpValidationProblemDetails>(params?: GetStudentAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttempts>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentAttemptsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentAttempts>>> = ({ signal }) => getStudentAttempts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentAttempts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentAttemptsQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentAttempts>>>
export type GetStudentAttemptsQueryError = ProblemDetails | HttpValidationProblemDetails


export function useGetStudentAttempts<TData = Awaited<ReturnType<typeof getStudentAttempts>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params: undefined |  GetStudentAttemptsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttempts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentAttempts>>,
          TError,
          Awaited<ReturnType<typeof getStudentAttempts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentAttempts<TData = Awaited<ReturnType<typeof getStudentAttempts>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttempts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentAttempts>>,
          TError,
          Awaited<ReturnType<typeof getStudentAttempts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentAttempts<TData = Awaited<ReturnType<typeof getStudentAttempts>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttempts>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStudentAttempts<TData = Awaited<ReturnType<typeof getStudentAttempts>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 params?: GetStudentAttemptsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttempts>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentAttemptsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getStudentAttemptByIdResponse200 = {
  data: StudentAttemptResponse
  status: 200
}

export type getStudentAttemptByIdResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getStudentAttemptByIdResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getStudentAttemptByIdResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getStudentAttemptByIdResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getStudentAttemptByIdResponseSuccess = (getStudentAttemptByIdResponse200) & {
  headers: Headers;
};
export type getStudentAttemptByIdResponseError = (getStudentAttemptByIdResponse401 | getStudentAttemptByIdResponse403 | getStudentAttemptByIdResponse404 | getStudentAttemptByIdResponse500) & {
  headers: Headers;
};

export type getStudentAttemptByIdResponse = (getStudentAttemptByIdResponseSuccess | getStudentAttemptByIdResponseError)

export const getGetStudentAttemptByIdUrl = (attemptId: string,) => {




  return `/api/v1/student/attempts/${attemptId}`
}

export const getStudentAttemptById = async (attemptId: string, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getStudentAttemptByIdResponse> => {

  return sqlmoduleFetch<getStudentAttemptByIdResponse>(getGetStudentAttemptByIdUrl(attemptId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStudentAttemptByIdQueryKey = (attemptId: string,) => {
    return [
    `/api/v1/student/attempts/${attemptId}`
    ] as const;
    }


export const getGetStudentAttemptByIdQueryOptions = <TData = Awaited<ReturnType<typeof getStudentAttemptById>>, TError = ProblemDetails>(attemptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttemptById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentAttemptByIdQueryKey(attemptId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentAttemptById>>> = ({ signal }) => getStudentAttemptById(attemptId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: attemptId !== null && attemptId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentAttemptById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentAttemptByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentAttemptById>>>
export type GetStudentAttemptByIdQueryError = ProblemDetails


export function useGetStudentAttemptById<TData = Awaited<ReturnType<typeof getStudentAttemptById>>, TError = ProblemDetails>(
 attemptId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttemptById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentAttemptById>>,
          TError,
          Awaited<ReturnType<typeof getStudentAttemptById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentAttemptById<TData = Awaited<ReturnType<typeof getStudentAttemptById>>, TError = ProblemDetails>(
 attemptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttemptById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentAttemptById>>,
          TError,
          Awaited<ReturnType<typeof getStudentAttemptById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentAttemptById<TData = Awaited<ReturnType<typeof getStudentAttemptById>>, TError = ProblemDetails>(
 attemptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttemptById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStudentAttemptById<TData = Awaited<ReturnType<typeof getStudentAttemptById>>, TError = ProblemDetails>(
 attemptId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAttemptById>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentAttemptByIdQueryOptions(attemptId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






