/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Задание, встречающееся в доступном журнале попыток.
 */
export interface AttemptTaskFilterOptionResponse {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  topicId?: string | null;
  /** @nullable */
  topicName?: string | null;
  isAvailable?: boolean;
}
