/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { AttemptListItemResponseReason } from './attemptListItemResponseReason';
import type { AttemptListItemResponseStatus } from './attemptListItemResponseStatus';

/**
 * Элемент списка журнала попыток без тяжёлого snapshot.
 */
export interface AttemptListItemResponse {
  id: string;
  userId: string;
  studentName: string;
  taskId: string;
  submittedSql: string;
  status: AttemptListItemResponseStatus;
  isCorrect: boolean;
  reason: AttemptListItemResponseReason;
  /**
     * Количество строк, прочитанных для сравнения в рамках внутреннего comparison-лимита. Это не общее количество строк полного неограниченного результата; returnedRowCount содержит число строк публичного snapshot, а resultRowLimit — его отдельный лимит.
     * @nullable
     */
  rowCount: number | null;
  /** @nullable */
  durationMs: number | null;
  /** @nullable */
  errorMessage: string | null;
  startedAt: string;
  finishedAt: string;
  createdById: string;
  createdAt: string;
  updatedById: string;
  updatedAt: string;
  /** @nullable */
  taskName: string | null;
  /** @nullable */
  topicName: string | null;
  /** @nullable */
  publicError: string | null;
  /** @nullable */
  createdByName: string | null;
  /** @nullable */
  updatedByName: string | null;
  /** @nullable */
  progressId: string | null;
  /** @nullable */
  validationVersionId: string | null;
  /** @nullable */
  attemptNumber: number | null;
  /** @nullable */
  score: number | null;
}
