/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Студент, встречающийся в доступном журнале попыток.
 */
export interface AttemptStudentFilterOptionResponse {
  id?: string;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  email?: string | null;
  isAvailable?: boolean;
}
