/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Тема, встречающаяся в доступном журнале попыток.
 */
export interface AttemptTopicFilterOptionResponse {
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  path?: string | null;
  isAvailable?: boolean;
}
