/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { AttemptCheckResultResponse } from './attemptCheckResultResponse';
import type { AttemptHintResponse } from './attemptHintResponse';

/**
 * Составная оценка попытки и актуальное состояние progress.
 */
export interface AttemptScoringResponse {
  attemptId: string;
  progressId: string;
  validationVersionId: string;
  attemptNumber: number;
  score: number;
  bestScore: number;
  passingScore: number;
  isPassed: boolean;
  attemptsUsed: number;
  /** @nullable */
  attemptsRemaining: number | null;
  canSubmit: boolean;
  canFinalize: boolean;
  checks: AttemptCheckResultResponse[];
  hints: AttemptHintResponse[];
}
