/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { AttemptCheckResultResponseKind } from './attemptCheckResultResponseKind';
import type { AttemptCheckResultResponseStatus } from './attemptCheckResultResponseStatus';

/**
 * Безопасный результат одного критерия в попытке.
 */
export interface AttemptCheckResultResponse {
  kind: AttemptCheckResultResponseKind;
  status: AttemptCheckResultResponseStatus;
  weight: number;
  awardedScore: number;
  /** @nullable */
  message: string | null;
}
