/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { CheckReason } from './checkReason';
import type { ExecutionStatus } from './executionStatus';

/**
 * Ответ с данными попытки выполнения задания.
 */
export interface AttemptResponse {
  id?: string;
  userId?: string;
  taskId?: string;
  submittedSql?: string;
  status?: ExecutionStatus;
  isCorrect?: boolean;
  reason?: CheckReason;
  /** @nullable */
  rowCount?: number | null;
  /** @nullable */
  durationMs?: number | null;
  /** @nullable */
  errorMessage?: string | null;
  startedAt?: string;
  finishedAt?: string;
  createdById?: string;
  createdAt?: string;
  updatedById?: string;
  updatedAt?: string;
}
