/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { AttemptResponseReason } from './attemptResponseReason';
import type { AttemptResponseResultSnapshotState } from './attemptResponseResultSnapshotState';
import type { AttemptResponseStatus } from './attemptResponseStatus';
import type { AttemptScoringResponse } from './attemptScoringResponse';

/**
 * Ответ с данными попытки выполнения задания.
 */
export interface AttemptResponse {
  id: string;
  userId: string;
  studentName: string;
  taskId: string;
  submittedSql: string;
  status: AttemptResponseStatus;
  isCorrect: boolean;
  reason: AttemptResponseReason;
  /**
     * Количество строк, прочитанных для сравнения в рамках внутреннего comparison-лимита. Это не общее количество строк полного неограниченного результата; returnedRowCount содержит число строк публичного snapshot, а resultRowLimit — его отдельный лимит.
     * @nullable
     */
  rowCount: number | null;
  /** @nullable */
  durationMs: number | null;
  /** @nullable */
  errorMessage: string | null;
  startedAt: string;
  finishedAt: string;
  createdById: string;
  createdAt: string;
  updatedById: string;
  updatedAt: string;
  resultSnapshotState: AttemptResponseResultSnapshotState;
  /** @nullable */
  taskName: string | null;
  /** @nullable */
  topicName: string | null;
  /** @nullable */
  publicError: string | null;
  /** @nullable */
  createdByName: string | null;
  /** @nullable */
  updatedByName: string | null;
  /** @nullable */
  actualColumns: string[] | null;
  /** @nullable */
  actualRows: ((string | null)[])[] | null;
  /** @nullable */
  returnedRowCount: number | null;
  isResultTruncated: boolean;
  /** @nullable */
  resultRowLimit: number | null;
  /** @nullable */
  resultSnapshotCreatedAt: string | null;
  /** @nullable */
  resultSnapshotExpiresAt: string | null;
  /** Составная оценка попытки и актуальное состояние progress. */
  scoring: AttemptScoringResponse | null;
}
