/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { AttemptHintResponseGroup } from './attemptHintResponseGroup';

/**
 * Подсказка, разрешённая текущей validation version.
 */
export interface AttemptHintResponse {
  group: AttemptHintResponseGroup;
  message: string;
}
