/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными значения параметра атрибута.
 */
export interface AttributeParameterValueResponse {
  /** Идентификатор значения параметра. */
  id?: string;
  /** Идентификатор мета-атрибута (колонки). */
  metaAttributeId?: string;
  /** Идентификатор определения параметра физического типа. */
  parameterDefinitionId?: string;
  /** Значение параметра. */
  parameterValue?: string;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания записи. */
  createdAt?: string;
  /** Идентификатор пользователя, последним обновившего запись. */
  updatedById?: string;
  /** Дата и время последнего обновления записи. */
  updatedAt?: string;
}
