/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { BatchTableRowsResponseCreatedIds } from './batchTableRowsResponseCreatedIds';
import type { TableRowResponse } from './tableRowResponse';

export interface BatchTableRowsResponse {
  schemaVersion: string;
  createdIds: BatchTableRowsResponseCreatedIds;
  rows: TableRowResponse[];
}
