/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными значения ячейки (EAV).
 */
export interface CellValueResponse {
  /** Идентификатор значения ячейки. */
  id?: string;
  /** Идентификатор строки данных, которой принадлежит ячейка. */
  dataRecordId?: string;
  /** Идентификатор мета-атрибута (столбца), которому соответствует значение. */
  metaAttributeId?: string;
  /**
     * Текстовое значение ячейки (null, если не задано).
     * @nullable
     */
  textValue?: string | null;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания записи. */
  createdAt?: string;
  /** Идентификатор пользователя, последним обновившего запись. */
  updatedById?: string;
  /** Дата и время последнего обновления записи. */
  updatedAt?: string;
}
