/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Значение параметра физического типа для колонки-черновика.
 */
export interface ColumnParameterDraft {
  /** Идентификатор определения параметра. */
  parameterDefinitionId?: string;
  /** Значение параметра (например, «255» для VARCHAR(255)). */
  value?: string;
}
