/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ColumnParameterDraft } from './columnParameterDraft';

/**
 * Черновик колонки с временным идентификатором.
 */
export interface ColumnDraft {
  /** Временный строковый идентификатор (уникальный внутри запроса). */
  tempId?: string;
  /** Имя колонки в целевой БД. */
  name?: string;
  /** Идентификатор физического типа данных. */
  physicalTypeId?: string;
  /** Признак первичного ключа. */
  isPrimaryKey?: boolean;
  /** Признак обязательности (NOT NULL). */
  isRequired?: boolean;
  /** Порядок колонки в таблице (≥ 0). */
  sortOrder?: number;
  /** Значения параметров физического типа (например, длина для VARCHAR). */
  parameters?: ColumnParameterDraft[];
}
