/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface CreateTargetDbFromDdlRequest {
  /** @nullable */
  dbmsId?: string | null;
  /** @nullable */
  dbName?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  isReadOnly?: boolean | null;
  /** @nullable */
  ddlScript?: string | null;
}
