/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание эталонного SQL-запроса.
 */
export interface CreateSqlQueryRequest {
  /** Идентификатор целевой БД (датасет для выполнения запроса). */
  targetDbId?: string;
  /** Текст SQL-запроса (не пустой). */
  queryText?: string;
  /** Если `true` — порядок колонок в ответе обязателен. */
  strictColumnOrder?: boolean;
  /** Если `true` — порядок строк в ответе обязателен. */
  strictRowOrder?: boolean;
}
