/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ReferenceQueryRequest } from './referenceQueryRequest';

/**
 * Запрос на создание SQL-задания.
 */
export interface CreateSqlTaskRequest {
  /**
     * Идентификатор темы, к которой относится задание.
     * @nullable
     */
  topicId?: string | null;
  /**
     * Название задания (не пустое, не более 300 символов).
     * @nullable
     */
  taskName?: string | null;
  /**
     * Текст условия задания (не пустое).
     * @nullable
     */
  taskText?: string | null;
  /**
     * Уровень сложности задания (1–5).
     * @nullable
     */
  difficultyLevel?: number | null;
  /** Новое эталонное решение задания. */
  referenceQuery?: ReferenceQueryRequest | null;
}
