/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание строки данных (EAV-якорь).
 */
export interface CreateDataRecordRequest {
  /** Идентификатор мета-таблицы, которой принадлежит строка. */
  metaTableId?: string;
  /**
     * Опциональный порядок отображения строки (≥ 0).
     * @nullable
     */
  sortOrder?: number | null;
}
