/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { RelationshipDraft } from './relationshipDraft';
import type { TableDraft } from './tableDraft';

/**
 * Запрос на построение схемы в песочнице (с временными идентификаторами).
 */
export interface CreateSchemaRequest {
  /** Идентификатор СУБД из справочника. */
  dbmsId?: string;
  /** Название схемы (или базы данных). */
  schemaName?: string;
  /** Список таблиц-черновиков. */
  tables?: TableDraft[];
  /** Список связей между колонками (Foreign Key). */
  relationships?: RelationshipDraft[];
}
