/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание мета-таблицы.
 */
export interface CreateMetaTableRequest {
  /** Идентификатор целевой БД, которой принадлежит таблица. */
  targetDbId?: string;
  /** Название таблицы (не пустое, максимум 200 символов). */
  tableName?: string;
  /**
     * Описание таблицы (необязательно, максимум 1000 символов).
     * @nullable
     */
  description?: string | null;
}
