/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание значения параметра атрибута.
 */
export interface CreateAttributeParameterValueRequest {
  /** Идентификатор мета-атрибута (колонки), которому принадлежит значение. */
  metaAttributeId?: string;
  /** Идентификатор определения параметра физического типа. */
  parameterDefinitionId?: string;
  /** Значение параметра (не более 500 символов). */
  parameterValue?: string;
}
