/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { TargetDbSchemaResponse } from './targetDbSchemaResponse';

export interface CreateTargetDbFromDdlResponse {
  targetDbId?: string;
  /** Согласованный снимок логической схемы учебной базы. */
  schema?: TargetDbSchemaResponse;
}
