/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание мета-атрибута (колонки) таблицы.
 */
export interface CreateMetaAttributeRequest {
  /** Идентификатор мета-таблицы, которой принадлежит колонка. */
  metaTableId?: string;
  /** Идентификатор физического типа данных колонки. */
  physicalTypeId?: string;
  /** Название колонки (не более 200 символов). */
  attributeName?: string;
  /** Признак первичного ключа. */
  isPrimaryKey?: boolean;
  /** Признак обязательности значения. */
  isRequired?: boolean;
  /** Порядок отображения колонки (≥ 0). */
  sortOrder?: number;
}
