/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание SQL-задания.
 */
export interface CreateSqlTaskRequest {
  /** Идентификатор темы, к которой относится задание. */
  topicId?: string;
  /** Идентификатор эталонного SQL-запроса (определяет целевую БД). */
  sqlQueryId?: string;
  /** Название задания (не пустое, не более 300 символов). */
  taskName?: string;
  /** Текст условия задания (не пустое). */
  taskText?: string;
  /** Уровень сложности задания (1–5). */
  difficultyLevel?: number;
}
