/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание физического типа данных.
 */
export interface CreatePhysicalTypeRequest {
  /** Идентификатор СУБД, которой принадлежит тип данных. */
  dbmsId?: string;
  /** Название физического типа данных (не более 100 символов). */
  typeName?: string;
}
