/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание темы тренажёра.
 */
export interface CreateTopicRequest {
  /** Название темы (не пустое, не более 300 символов). */
  topicName?: string;
  /**
     * Идентификатор родительской темы. `null` — корневая тема.
     * @nullable
     */
  parentTopicId?: string | null;
}
