/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание связи между двумя мета-атрибутами.
 */
export interface CreateMetaRelationshipRequest {
  /** Название связи (FK). Обязательно, до 200 символов. */
  relationshipName?: string;
  /** Id исходного мета-атрибута (сторона «многие»). */
  sourceAttributeId?: string;
  /** Id целевого мета-атрибута (сторона «один»). Должен отличаться от SourceAttributeId. */
  targetAttributeId?: string;
  /**
     * Правило при удалении (CASCADE, RESTRICT, SET NULL, SET DEFAULT, NO ACTION). До 50 символов.
     * @nullable
     */
  deleteRule?: string | null;
  /**
     * Правило при обновлении. До 50 символов.
     * @nullable
     */
  updateRule?: string | null;
}
