/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на создание целевой БД-песочницы.
 */
export interface CreateTargetDbRequest {
  /** Идентификатор СУБД из справочника (`DbmsDictionary.Id`). */
  dbmsId?: string;
  /** Уникальное имя создаваемой БД-песочницы. */
  dbName?: string;
  /**
     * Необязательное описание назначения БД.
     * @nullable
     */
  description?: string | null;
  /** Если `true` — запросы к БД выполняются только на чтение. */
  isReadOnly?: boolean;
}
