/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Канонический контекст текущего платформенного запуска.
 */
export interface CurrentModuleSessionResponse {
  /** Идентификатор SQL-задания, доверенно полученный от Education. */
  taskId?: string;
  /** Канонический адрес возврата в платформу. */
  returnUrl?: string;
  /**
     * Время окончания сессии или null для сессии без лимита.
     * @nullable
     */
  expiresAt?: string | null;
}
