/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными строки (EAV-якорь).
 */
export interface DataRecordResponse {
  /** Идентификатор строки данных. */
  id?: string;
  /** Идентификатор мета-таблицы, которой принадлежит строка. */
  metaTableId?: string;
  /**
     * Порядок отображения строки (null, если не задан).
     * @nullable
     */
  sortOrder?: number | null;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания записи. */
  createdAt?: string;
  /** Идентификатор пользователя, последним обновившего запись. */
  updatedById?: string;
  /** Дата и время последнего обновления записи. */
  updatedAt?: string;
}
