/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { DataRecordResponse } from './dataRecordResponse';

/**
 * Ответ в виде страницы с информацией о элементах и их кол-ве
 */
export interface DataRecordResponsePageResponse {
  /**
     * Количество элементов
     * @nullable
     */
  count?: number | null;
  /** Список элементов */
  items?: DataRecordResponse[];
}
