/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { HintGroup } from './hintGroup';
import type { SqlConstruct } from './sqlConstruct';
import type { ValidationCheckKind } from './validationCheckKind';

/**
 * Возможности проверки SQL для конкретной СУБД.
 */
export interface DbmsValidationCapabilitiesResponse {
  dbmsId: string;
  supportedCheckKinds: ValidationCheckKind[];
  supportedConstructs: SqlConstruct[];
  supportedHintGroups: HintGroup[];
  maxAttemptsLimit: number;
  analyzerVersion: string;
}
