/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type ExecutionStatus = typeof ExecutionStatus[keyof typeof ExecutionStatus];


export const ExecutionStatus = {
  Succeeded: 'Succeeded',
  Error: 'Error',
  TimedOut: 'TimedOut',
} as const;
