/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAttemptTaskFilterOptionsParams = {
Search?: string;
Id?: string;
TopicId?: string;
Offset?: number;
Limit?: number;
};
