/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllAttemptsStatus = typeof GetAllAttemptsStatus[keyof typeof GetAllAttemptsStatus];


export const GetAllAttemptsStatus = {
  Succeeded: 'Succeeded',
  Error: 'Error',
  TimedOut: 'TimedOut',
} as const;
