/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllTopicsParams = {
/**
 * Количество пропускаемых записей. Минимум: 0. По умолчанию: 0.
 */
Offset?: number;
/**
 * Максимальное количество записей на странице. Диапазон: 1–100. По умолчанию: 20.
 */
Limit?: number;
};
