/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllMetaRelationshipsParams = {
/**
 * Смещение (число пропускаемых записей). Минимум 0.
 */
Offset?: number;
/**
 * Максимальное число записей в ответе. От 1 до 100.
 */
Limit?: number;
/**
 * Опциональный фильтр: если задан, возвращаются только связи, в которых данный
 * мета-атрибут участвует в роли SourceAttribute или TargetAttribute.
 */
AttributeId?: string;
};
