/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { GetAllAttemptsFinalizationReason } from './getAllAttemptsFinalizationReason';
import type { GetAllAttemptsStatus } from './getAllAttemptsStatus';

export type GetAllAttemptsParams = {
/**
 * Количество пропускаемых записей. Минимум: 0. По умолчанию: 0.
 */
Offset?: number;
/**
 * Максимальное количество возвращаемых записей. Диапазон: 1–100. По умолчанию: 20.
 */
Limit?: number;
/**
 * Необязательный фильтр по заданию.
 */
TaskId?: string;
/**
 * Необязательный фильтр по студенту.
 */
UserId?: string;
/**
 * Необязательный фильтр по теме.
 */
TopicId?: string;
/**
 * Необязательный фильтр по статусу выполнения.
 */
Status?: GetAllAttemptsStatus;
/**
 * Необязательный фильтр по корректности результата.
 */
IsCorrect?: boolean;
/**
 * Нижняя граница даты начала.
 */
DateFrom?: string;
/**
 * Верхняя граница даты начала.
 */
DateTo?: string;
/**
 * Необязательный фильтр по прохождению.
 */
ProgressId?: string;
/**
 * Необязательный фильтр по версии проверки.
 */
ValidationVersionId?: string;
/**
 * Минимальный балл включительно, от 0 до 100.
 */
ScoreFrom?: number;
/**
 * Максимальный балл включительно, от 0 до 100.
 */
ScoreTo?: number;
/**
 * Причина финализации связанного прохождения.
 */
FinalizationReason?: GetAllAttemptsFinalizationReason;
};
