/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllAttemptsParams = {
/**
 * Количество пропускаемых записей. Минимум: 0. По умолчанию: 0.
 */
Offset?: number;
/**
 * Максимальное количество возвращаемых записей. Диапазон: 1–100. По умолчанию: 20.
 */
Limit?: number;
/**
 * Необязательный фильтр по заданию.
 */
TaskId?: string;
/**
 * Необязательный фильтр по студенту.
 */
UserId?: string;
};
