/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllCellValuesParams = {
/**
 * Смещение от начала списка (≥ 0).
 */
Offset?: number;
/**
 * Количество записей на странице (1–100).
 */
Limit?: number;
};
