/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllMetaAttributesParams = {
/**
 * Смещение от начала списка (≥ 0).
 */
Offset?: number;
/**
 * Количество записей на странице (1–100).
 */
Limit?: number;
/**
 * Опциональный фильтр по мета-таблице — вернуть только колонки указанной таблицы.
 */
MetaTableId?: string;
};
