/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { GetAllSqlTasksPublicationStatus } from './getAllSqlTasksPublicationStatus';

export type GetAllSqlTasksParams = {
/**
 * Количество пропускаемых записей. Минимум: 0. По умолчанию: 0.
 */
Offset?: number;
/**
 * Максимальное количество записей на странице. Диапазон: 1–100. По умолчанию: 20.
 */
Limit?: number;
/**
 * Фильтр по теме.
 */
TopicId?: string;
/**
 * Поиск по названию.
 */
Name?: string;
/**
 * Фильтр по учебной базе.
 */
TargetDbId?: string;
/**
 * Фильтр по сложности.
 */
DifficultyLevel?: number;
/**
 * Фильтр по статусу публикации.
 */
PublicationStatus?: GetAllSqlTasksPublicationStatus;
};
