/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllMetaTablesParams = {
/**
 * Количество пропускаемых записей (>= 0). По умолчанию 0.
 */
Offset?: number;
/**
 * Размер страницы (1–100). По умолчанию 20.
 */
Limit?: number;
/**
 * Опциональный фильтр по целевой БД.
 */
TargetDbId?: string;
};
