/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetAllParameterDefinitionsParams = {
/**
 * Смещение (количество пропускаемых записей, ≥ 0).
 */
Offset?: number;
/**
 * Максимальное количество возвращаемых записей (1–100).
 */
Limit?: number;
/**
 * Опциональный фильтр по идентификатору физического типа.
 */
PhysicalTypeId?: string;
};
