/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetModuleTasksCatalogHeaders = {
/**
 * Секрет сервер-сервер интеграции Education и SqlModule.
 */
'X-Service-Key': string;
};
