/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { GetStudentAttemptsStatus } from './getStudentAttemptsStatus';

export type GetStudentAttemptsParams = {
TaskId?: string;
TopicId?: string;
Status?: GetStudentAttemptsStatus;
IsCorrect?: boolean;
DateFrom?: string;
DateTo?: string;
Offset?: number;
Limit?: number;
};
