/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetStudentAttemptsStatus = typeof GetStudentAttemptsStatus[keyof typeof GetStudentAttemptsStatus];


export const GetStudentAttemptsStatus = {
  Succeeded: 'Succeeded',
  Error: 'Error',
  TimedOut: 'TimedOut',
} as const;
