/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type GetTargetDbTableLookupValuesParams = {
/**
 * Колонка, значение которой будет сохранено во внешнем ключе.
 */
valueColumnId: string;
/**
 * Необязательная колонка с понятным пользователю названием.
 */
labelColumnId?: string;
/**
 * Подстрока для регистронезависимого поиска по значению и названию.
 * @maxLength 200
 */
search?: string;
/**
 * Количество пропускаемых строк. По умолчанию 0.
 * @minimum 0
 */
offset?: number;
/**
 * Размер страницы. По умолчанию 30.
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
