/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { HttpValidationProblemDetailsErrors } from './httpValidationProblemDetailsErrors';
import type { HttpValidationProblemDetailsViolationsItem } from './httpValidationProblemDetailsViolationsItem';

export interface HttpValidationProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  errors?: HttpValidationProblemDetailsErrors;
  code?: string;
  traceId?: string;
  violations?: HttpValidationProblemDetailsViolationsItem[];
  [key: string]: unknown;
}
