/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type HttpValidationProblemDetailsViolationsItem = {
  path?: string;
  code?: string;
  message?: string;
  severity?: string;
  affectedRows?: number;
};
