/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Одна строка связанной таблицы, доступная для выбора.
 */
export interface LookupValueItemResponse {
  rowId: string;
  value: string;
  label: string;
}
