/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { LookupValueItemResponse } from './lookupValueItemResponse';

/**
 * Страница вариантов значения внешнего ключа.
 */
export interface LookupValuesResponse {
  count: number;
  offset: number;
  limit: number;
  items: LookupValueItemResponse[];
}
