/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными связи между мета-атрибутами.
 */
export interface MetaRelationshipResponse {
  /** Идентификатор связи. */
  id?: string;
  /** Название связи (FK). */
  relationshipName?: string;
  /** Id исходного мета-атрибута. */
  sourceAttributeId?: string;
  /** Id целевого мета-атрибута. */
  targetAttributeId?: string;
  /**
     * Правило при удалении.
     * @nullable
     */
  deleteRule?: string | null;
  /**
     * Правило при обновлении.
     * @nullable
     */
  updateRule?: string | null;
  /** Id пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания. */
  createdAt?: string;
  /** Id пользователя, последним изменившего запись. */
  updatedById?: string;
  /** Дата и время последнего изменения. */
  updatedAt?: string;
}
