/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными мета-таблицы.
 */
export interface MetaTableResponse {
  /** Идентификатор мета-таблицы. */
  id?: string;
  /** Идентификатор целевой БД. */
  targetDbId?: string;
  /** Название таблицы. */
  tableName?: string;
  /**
     * Описание таблицы.
     * @nullable
     */
  description?: string | null;
  /** Идентификатор создавшего пользователя. */
  createdById?: string;
  /** Дата и время создания. */
  createdAt?: string;
  /** Идентификатор последнего редактора. */
  updatedById?: string;
  /** Дата и время последнего обновления. */
  updatedAt?: string;
}
