/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными мета-атрибута (колонки) таблицы.
 */
export interface MetaAttributeResponse {
  /** Идентификатор мета-атрибута. */
  id?: string;
  /** Идентификатор мета-таблицы. */
  metaTableId?: string;
  /** Идентификатор физического типа данных. */
  physicalTypeId?: string;
  /** Название колонки. */
  attributeName?: string;
  /** Признак первичного ключа. */
  isPrimaryKey?: boolean;
  /** Признак обязательности значения. */
  isRequired?: boolean;
  /** Порядок отображения колонки. */
  sortOrder?: number;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания записи. */
  createdAt?: string;
  /** Идентификатор пользователя, последним обновившего запись. */
  updatedById?: string;
  /** Дата и время последнего обновления записи. */
  updatedAt?: string;
}
