/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на перемещение темы в иерархии.
 */
export interface MoveTopicRequest {
  /**
     * Идентификатор нового родителя. `null` — сделать корневой темой.
     * @nullable
     */
  parentTopicId?: string | null;
}
