/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными определения параметра физического типа данных.
 */
export interface ParameterDefinitionResponse {
  /** Идентификатор определения параметра. */
  id?: string;
  /** Идентификатор физического типа, которому принадлежит параметр. */
  physicalTypeId?: string;
  /** Ключ параметра. */
  parameterKey?: string;
  /** Отображаемое название параметра. */
  displayName?: string;
  /** Тип поля ввода. */
  inputType?: string;
  /**
     * Значение по умолчанию.
     * @nullable
     */
  defaultValue?: string | null;
  /** Порядок отображения. */
  sortOrder?: number;
  /** Шаблон SQL-фрагмента с плейсхолдером {value}. */
  sqlFragment?: string;
  /** Признак обязательности параметра. */
  isRequired?: boolean;
  /**
     * Префикс значения в SQL-выражении.
     * @nullable
     */
  valuePrefix?: string | null;
  /**
     * Суффикс значения в SQL-выражении.
     * @nullable
     */
  valueSuffix?: string | null;
  /**
     * Разделитель для списочных значений.
     * @nullable
     */
  separator?: string | null;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания записи. */
  createdAt?: string;
  /** Идентификатор пользователя, последним обновившего запись. */
  updatedById?: string;
  /** Дата и время последнего обновления записи. */
  updatedAt?: string;
}
