/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Ответ с данными физического типа данных.
 */
export interface PhysicalTypeResponse {
  /** Идентификатор физического типа данных. */
  id?: string;
  /** Идентификатор СУБД, которой принадлежит тип. */
  dbmsId?: string;
  /** Название физического типа данных. */
  typeName?: string;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания записи. */
  createdAt?: string;
  /** Идентификатор пользователя, последним обновившего запись. */
  updatedById?: string;
  /** Дата и время последнего обновления записи. */
  updatedAt?: string;
}
