/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Причина, по которой задание нельзя опубликовать или запустить.
 */
export interface PublishBlockerResponse {
  /** Стабильный machine-код, например `SqlTask.ValidationVersionNotPublished`. */
  code: string;
  /** Понятное преподавателю описание. */
  message: string;
}
