/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос публикации проверенной immutable validation version.
 */
export interface PublishTaskValidationRequest {
  /** @nullable */
  version?: string | null;
}
