/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Черновик связи (Foreign Key) между двумя колонками.
 */
export interface RelationshipDraft {
  /** Название ограничения FK. */
  name?: string;
  /** TempId колонки, содержащей Foreign Key. */
  sourceColumnTempId?: string;
  /** TempId колонки, на которую ссылается Foreign Key. */
  targetColumnTempId?: string;
  /**
     * Действие при удалении родительской строки (CASCADE, RESTRICT, SET NULL, NO ACTION) или `null`.
     * @nullable
     */
  deleteRule?: string | null;
  /**
     * Действие при обновлении родительской строки (CASCADE, RESTRICT, SET NULL, NO ACTION) или `null`.
     * @nullable
     */
  updateRule?: string | null;
}
