/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface SchemaCapabilitiesResponse {
  canEditSchema: boolean;
  canValidateSchema: boolean;
  canApplySchema: boolean;
  canEditData: boolean;
  canDeleteTargetDb: boolean;
  /** @nullable */
  schemaEditBlockReason?: string | null;
  /** @nullable */
  dataEditBlockReason?: string | null;
  /** @nullable */
  deleteTargetDbBlockReason?: string | null;
}
