/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { SchemaColumnMap } from './schemaColumnMap';

/**
 * Карта таблицы: TempId → реальный MetaTable.Id.
 */
export interface SchemaTableMap {
  /** Временный Id таблицы из черновика. */
  tempId?: string;
  /** Реальный Id созданной MetaTable. */
  id?: string;
  /** Карты атрибутов таблицы. */
  columns?: SchemaColumnMap[];
}
