/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface SchemaRelationshipResponse {
  id: string;
  name: string;
  sourceColumnId: string;
  targetColumnId: string;
  /** @nullable */
  deleteRule?: string | null;
  /** @nullable */
  updateRule?: string | null;
}
