/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface SchemaRelationshipDraft {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  tempId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  sourceColumnRef?: string | null;
  /** @nullable */
  targetColumnRef?: string | null;
  /** @nullable */
  deleteRule?: string | null;
  /** @nullable */
  updateRule?: string | null;
}
