/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { SchemaColumnResponse } from './schemaColumnResponse';

export interface SchemaTableResponse {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  sortOrder: number;
  columns: SchemaColumnResponse[];
}
