/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { SchemaChangeResponse } from './schemaChangeResponse';

export interface SchemaValidationResponse {
  isValid: boolean;
  requiresConfirmation?: boolean;
  /** @nullable */
  normalizedVersion?: string | null;
  warnings: string[];
  changes?: SchemaChangeResponse[];
  destructiveChanges?: SchemaChangeResponse[];
  /** @nullable */
  confirmationToken?: string | null;
  /** @nullable */
  ddlPreview?: string | null;
}
