/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface SchemaParameterResponse {
  parameterDefinitionId: string;
  parameterKey: string;
  displayName: string;
  inputType: string;
  /** @nullable */
  value?: string | null;
  isRequired: boolean;
}
