/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Карта атрибута: TempId → реальный MetaAttribute.Id.
 */
export interface SchemaColumnMap {
  /** Временный Id колонки из черновика. */
  tempId?: string;
  /** Реальный Id созданного MetaAttribute. */
  id?: string;
}
