/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { SqlQueryResponse } from './sqlQueryResponse';

/**
 * Ответ в виде страницы с информацией о элементах и их кол-ве
 */
export interface SqlQueryResponsePageResponse {
  /**
     * Количество элементов
     * @nullable
     */
  count?: number | null;
  /** Список элементов */
  items?: SqlQueryResponse[];
}
