/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Статус публикации задания.
 */
export type SqlTaskResponsePublicationStatus = typeof SqlTaskResponsePublicationStatus[keyof typeof SqlTaskResponsePublicationStatus];


export const SqlTaskResponsePublicationStatus = {
  Draft: 'Draft',
  Published: 'Published',
  Archived: 'Archived',
} as const;
