/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Данные SQL-задания.
 */
export interface SqlTaskResponse {
  /** Уникальный идентификатор задания. */
  id?: string;
  /** Идентификатор темы. */
  topicId?: string;
  /** Идентификатор эталонного SQL-запроса. */
  sqlQueryId?: string;
  /** Название задания. */
  taskName?: string;
  /** Текст условия задания. */
  taskText?: string;
  /** Уровень сложности (1–5). */
  difficultyLevel?: number;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания (UTC). */
  createdAt?: string;
  /** Идентификатор пользователя, последним изменившего запись. */
  updatedById?: string;
  /** Дата и время последнего изменения (UTC). */
  updatedAt?: string;
}
