/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Refresh-токен, выданный при standalone-входе или предыдущем обновлении.
 */
export interface StandaloneRefreshRequest {
  refreshToken?: string;
}
