/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Учётные данные для standalone-входа.
 */
export interface StandaloneLoginRequest {
  email?: string;
  password?: string;
}
