/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type StudentAttemptResponseStatus = typeof StudentAttemptResponseStatus[keyof typeof StudentAttemptResponseStatus];


export const StudentAttemptResponseStatus = {
  Succeeded: 'Succeeded',
  Error: 'Error',
  TimedOut: 'TimedOut',
} as const;
