/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { StudentTaskHintsResponse } from './studentTaskHintsResponse';
import type { StudentTaskProgressResponse } from './studentTaskProgressResponse';

/**
 * Безопасная validation-часть student task details.
 */
export interface StudentTaskValidationResponse {
  passingScore: number;
  /** @nullable */
  maxAttempts: number | null;
  /** Текущее прохождение SQL-задания. */
  progress: StudentTaskProgressResponse | null;
  /** Разрешённые преподавателем подсказки по validation version. */
  hints: StudentTaskHintsResponse;
}
