/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { StudentSchemaForeignKeyResponse } from './studentSchemaForeignKeyResponse';
import type { StudentSchemaTableResponse } from './studentSchemaTableResponse';

/**
 * Безопасное представление структуры учебной базы для студента.
 */
export interface StudentTaskSchemaResponse {
  databaseName?: string;
  dbms?: string;
  tables?: StudentSchemaTableResponse[];
  foreignKeys?: StudentSchemaForeignKeyResponse[];
}
