/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Таблица, раскрытая студенту как безопасная подсказка.
 */
export interface StudentHintTableResponse {
  id: string;
  name: string;
}
