/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { StudentExecutionLimitsResponse } from './studentExecutionLimitsResponse';
import type { StudentTaskValidationResponse } from './studentTaskValidationResponse';

export interface StudentTaskDetailsResponse {
  id: string;
  topicId: string;
  topicName: string;
  taskName: string;
  taskText: string;
  difficultyLevel: number;
  dbmsName: string;
  executionLimits: StudentExecutionLimitsResponse;
  /** Безопасная validation-часть student task details. */
  validation: StudentTaskValidationResponse | null;
}
