/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface StudentTaskResponse {
  id?: string;
  topicId?: string;
  topicName?: string;
  taskName?: string;
  taskTextPreview?: string;
  difficultyLevel?: number;
  dbmsName?: string;
}
