/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type StudentAttemptListItemResponseStatus = typeof StudentAttemptListItemResponseStatus[keyof typeof StudentAttemptListItemResponseStatus];


export const StudentAttemptListItemResponseStatus = {
  Succeeded: 'Succeeded',
  Error: 'Error',
  TimedOut: 'TimedOut',
} as const;
