/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type StudentAttemptResponseResultSnapshotState = typeof StudentAttemptResponseResultSnapshotState[keyof typeof StudentAttemptResponseResultSnapshotState];


export const StudentAttemptResponseResultSnapshotState = {
  NotStored: 'NotStored',
  Available: 'Available',
  NotProduced: 'NotProduced',
  Expired: 'Expired',
} as const;
