/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { StudentSchemaColumnPairResponse } from './studentSchemaColumnPairResponse';

export interface StudentSchemaForeignKeyResponse {
  id?: string;
  name?: string;
  fromTableId?: string;
  toTableId?: string;
  columnPairs?: StudentSchemaColumnPairResponse[];
}
