/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type StudentTaskProgressResponseStatus = typeof StudentTaskProgressResponseStatus[keyof typeof StudentTaskProgressResponseStatus];


export const StudentTaskProgressResponseStatus = {
  Active: 'Active',
  Finalizing: 'Finalizing',
  CompletionPending: 'CompletionPending',
  CompletionFailed: 'CompletionFailed',
  Completed: 'Completed',
  Expired: 'Expired',
} as const;
