/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type StudentTaskProgressResponseFinalizationReason = typeof StudentTaskProgressResponseFinalizationReason[keyof typeof StudentTaskProgressResponseFinalizationReason] | null;


export const StudentTaskProgressResponseFinalizationReason = {
  Manual: 'Manual',
  PerfectScore: 'PerfectScore',
  AttemptsExhausted: 'AttemptsExhausted',
  Expired: 'Expired',
  EducationClosed: 'EducationClosed',
  Restarted: 'Restarted',
} as const;
