/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface StudentSchemaColumnResponse {
  id?: string;
  name?: string;
  dataType?: string;
  isNullable?: boolean;
  isPrimaryKey?: boolean;
}
