/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface StudentTopicResponse {
  id?: string;
  topicName?: string;
  /** @nullable */
  parentTopicId?: string | null;
  /** @nullable */
  description?: string | null;
  publishedTasksCount?: number;
}
