/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { HintGroup } from './hintGroup';
import type { SqlConstruct } from './sqlConstruct';
import type { StudentHintTableResponse } from './studentHintTableResponse';

/**
 * Разрешённые преподавателем подсказки по validation version.
 */
export interface StudentTaskHintsResponse {
  groups: HintGroup[];
  requiredConstructs: SqlConstruct[];
  forbiddenConstructs: SqlConstruct[];
  requiredTables: StudentHintTableResponse[];
  forbiddenTables: StudentHintTableResponse[];
}
