/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на отправку попытки выполнения задания.
 */
export interface SubmitAttemptRequest {
  taskId?: string;
  submittedSql?: string;
}
