/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { CheckReason } from './checkReason';
import type { ExecutionStatus } from './executionStatus';

/**
 * Результат проверки попытки выполнения задания.
 */
export interface SubmitAttemptResponse {
  attemptId?: string;
  status?: ExecutionStatus;
  isCorrect?: boolean;
  reason?: CheckReason;
  /** @nullable */
  rowCount?: number | null;
  /** @nullable */
  durationMs?: number | null;
  /** @nullable */
  errorMessage?: string | null;
  actualColumns?: string[];
  actualRows?: string[][];
}
