/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type SubmitAttemptResponseResultSnapshotState = typeof SubmitAttemptResponseResultSnapshotState[keyof typeof SubmitAttemptResponseResultSnapshotState];


export const SubmitAttemptResponseResultSnapshotState = {
  NotStored: 'NotStored',
  Available: 'Available',
  NotProduced: 'NotProduced',
  Expired: 'Expired',
} as const;
