/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type TableRowChangeOperation = typeof TableRowChangeOperation[keyof typeof TableRowChangeOperation];


export const TableRowChangeOperation = {
  Create: 'Create',
  Update: 'Update',
  Delete: 'Delete',
} as const;
