/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ColumnDraft } from './columnDraft';

/**
 * Черновик таблицы с временным идентификатором.
 */
export interface TableDraft {
  /** Временный строковый идентификатор (уникальный внутри запроса). */
  tempId?: string;
  /** Имя таблицы в целевой БД. */
  name?: string;
  /** Список колонок таблицы. */
  columns?: ColumnDraft[];
}
