/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { TableRowResponse } from './tableRowResponse';
import type { TableRowsColumnResponse } from './tableRowsColumnResponse';

export interface TableRowsResponse {
  count: number;
  offset: number;
  limit: number;
  schemaVersion: string;
  columns: TableRowsColumnResponse[];
  items: TableRowResponse[];
}
