/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type TargetDbSchemaResponseState = typeof TargetDbSchemaResponseState[keyof typeof TargetDbSchemaResponseState];


export const TargetDbSchemaResponseState = {
  Draft: 'Draft',
  Ready: 'Ready',
} as const;
