/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { HintGroup } from './hintGroup';
import type { TaskValidationConfigurationResponseState } from './taskValidationConfigurationResponseState';
import type { ValidationCheckResponse } from './validationCheckResponse';

/**
 * Текущая конфигурация проверки и активная опубликованная версия.
 */
export interface TaskValidationConfigurationResponse {
  /** Идентификатор задания. */
  taskId: string;
  /** Токен версии черновика; передаётся при сохранении и публикации. */
  version: string;
  /**
     * Идентификатор активной опубликованной версии. `null` — версия ни разу не публиковалась
     * (задание нельзя опубликовать или запустить). Отсутствие версии определяется только этим полем.
     * @nullable
     */
  validationVersionId: string | null;
  /**
     * Номер активной версии; `null`, если версия не публиковалась.
     * @nullable
     */
  validationVersionNumber: number | null;
  /** Состояние: `Draft` — версии нет или черновик изменён, `Published` — совпадает с активной. */
  state: TaskValidationConfigurationResponseState;
  /**
     * Черновик отличается от активной опубликованной версии. Если версии нет (`validationVersionId == null`),
     * значение `false`: сравнивать не с чем. Поле не означает отсутствие версии.
     */
  hasUnpublishedChanges: boolean;
  /** Проходной балл (1–100). */
  passingScore: number;
  /**
     * Лимит попыток; `null` — без ограничения.
     * @nullable
     */
  maxAttempts: number | null;
  /** Группы подсказок, видимые студенту. */
  visibleHintGroups: HintGroup[];
  /** Критерии оценки. */
  checks: ValidationCheckResponse[];
  /** Дата создания конфигурации. */
  createdAt: string;
  /** Дата последнего изменения черновика. */
  updatedAt: string;
  /**
     * Дата публикации активной версии; `null`, если версии нет.
     * @nullable
     */
  publishedAt: string | null;
}
