/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { HintGroup } from './hintGroup';
import type { TaskValidationConfigurationResponseState } from './taskValidationConfigurationResponseState';
import type { ValidationCheckResponse } from './validationCheckResponse';

/**
 * Текущая конфигурация проверки и активная опубликованная версия.
 */
export interface TaskValidationConfigurationResponse {
  taskId: string;
  version: string;
  /** @nullable */
  validationVersionId: string | null;
  /** @nullable */
  validationVersionNumber: number | null;
  state: TaskValidationConfigurationResponseState;
  hasUnpublishedChanges: boolean;
  passingScore: number;
  /** @nullable */
  maxAttempts: number | null;
  visibleHintGroups: HintGroup[];
  checks: ValidationCheckResponse[];
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  publishedAt: string | null;
}
