/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ValidationCheckPreviewResponse } from './validationCheckPreviewResponse';
import type { ValidationViolationResponse } from './validationViolationResponse';

/**
 * Предварительная проверка эталона по draft-конфигурации.
 */
export interface TaskValidationPreviewResponse {
  isValid: boolean;
  referenceScore: number;
  analyzerVersion: string;
  checks: ValidationCheckPreviewResponse[];
  violations: ValidationViolationResponse[];
}
