/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { HintGroup } from './hintGroup';
import type { ValidationCheckRequest } from './validationCheckRequest';

/**
 * Полная редактируемая конфигурация проверки задания.
 */
export interface TaskValidationConfigurationRequest {
  /** @nullable */
  version?: string | null;
  /** @nullable */
  passingScore?: number | null;
  /** @nullable */
  maxAttempts?: number | null;
  /** @nullable */
  visibleHintGroups?: HintGroup[] | null;
  /** @nullable */
  checks?: ValidationCheckRequest[] | null;
}
