/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type TaskValidationConfigurationResponseState = typeof TaskValidationConfigurationResponseState[keyof typeof TaskValidationConfigurationResponseState];


export const TaskValidationConfigurationResponseState = {
  Draft: 'Draft',
  Published: 'Published',
} as const;
