/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { TeacherTaskAttemptResponseStatus } from './teacherTaskAttemptResponseStatus';

/**
 * Краткая попытка студента.
 */
export interface TeacherTaskAttemptResponse {
  attemptId?: string;
  studentId?: string;
  studentName?: string;
  isCorrect?: boolean;
  status?: TeacherTaskAttemptResponseStatus;
  /** @nullable */
  durationMs?: number | null;
  finishedAt?: string;
  /** @nullable */
  attemptNumber?: number | null;
  /** @nullable */
  score?: number | null;
}
