/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type TeacherTaskAttemptResponseStatus = typeof TeacherTaskAttemptResponseStatus[keyof typeof TeacherTaskAttemptResponseStatus];


export const TeacherTaskAttemptResponseStatus = {
  Succeeded: 'Succeeded',
  Error: 'Error',
  TimedOut: 'TimedOut',
} as const;
