/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { TeacherTaskTableResponse } from './teacherTaskTableResponse';

/**
 * Учебная база в деталях задания.
 */
export interface TeacherTaskTargetDbResponse {
  targetDbId?: string;
  dbName?: string;
  dbmsName?: string;
  tables?: TeacherTaskTableResponse[];
}
