/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { TeacherTaskAttemptResponse } from './teacherTaskAttemptResponse';
import type { TeacherTaskDetailsResponsePublicationStatus } from './teacherTaskDetailsResponsePublicationStatus';
import type { TeacherTaskSqlQueryResponse } from './teacherTaskSqlQueryResponse';
import type { TeacherTaskTargetDbResponse } from './teacherTaskTargetDbResponse';

/**
 * Агрегированная read-модель деталей задания для преподавателя.
 */
export interface TeacherTaskDetailsResponse {
  /** Идентификатор задания. */
  taskId?: string;
  /** Идентификатор темы. */
  topicId?: string;
  /** Название темы. */
  topicName?: string;
  /** Название задания. */
  taskName?: string;
  /** Условие задания. */
  description?: string;
  /** Уровень сложности. */
  difficultyLevel?: number;
  /** Статус публикации. */
  publicationStatus?: TeacherTaskDetailsResponsePublicationStatus;
  /** Дата создания. */
  createdAt?: string;
  /** Дата последнего изменения. */
  updatedAt?: string;
  /** Идентификатор автора. */
  createdById?: string;
  /** Текущее эталонное решение. */
  sqlQuery?: TeacherTaskSqlQueryResponse;
  /** Учебная база эталонного решения. */
  targetDb?: TeacherTaskTargetDbResponse;
  /**
     * Можно ли изменять основные поля задания: название, условие и сложность.
     * Флаг не распространяется на тему, статус публикации и эталонное решение — для них действуют отдельные правила.
     */
  canEditTask?: boolean;
  /** Можно ли сейчас изменить эталонное решение отдельной операцией. */
  canEditReferenceQuery?: boolean;
  /**
     * Понятная пользователю причина запрета изменения эталона; null, если изменение разрешено.
     * @nullable
     */
  referenceQueryEditRestriction?: string | null;
  /** Общее количество попыток. */
  attemptsCount?: number;
  /** Последние попытки выполнения. */
  lastAttempts?: TeacherTaskAttemptResponse[];
  /** Можно ли опубликовать задание сейчас. */
  canPublish?: boolean;
  /** Можно ли архивировать задание сейчас. */
  canArchive?: boolean;
  /** Можно ли удалить задание сейчас. */
  canDelete?: boolean;
  /**
     * Причина запрета lifecycle-операции, если она общая.
     * @nullable
     */
  lifecycleRestriction?: string | null;
  /**
     * Отображаемое имя автора на момент создания задания.
     * @nullable
     */
  createdByName?: string | null;
}
