/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ExecutionStatus } from './executionStatus';

/**
 * Краткая попытка студента.
 */
export interface TeacherTaskAttemptResponse {
  attemptId?: string;
  studentId?: string;
  studentName?: string;
  isCorrect?: boolean;
  status?: ExecutionStatus;
  /** @nullable */
  durationMs?: number | null;
  finishedAt?: string;
}
