/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Краткое описание таблицы учебной базы.
 */
export interface TeacherTaskTableResponse {
  tableName?: string;
  columnsCount?: number;
}
