/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { PublicationStatus } from './publicationStatus';
import type { TeacherTaskAttemptResponse } from './teacherTaskAttemptResponse';
import type { TeacherTaskSqlQueryResponse } from './teacherTaskSqlQueryResponse';
import type { TeacherTaskTargetDbResponse } from './teacherTaskTargetDbResponse';

/**
 * Агрегированная read-модель деталей задания для преподавателя.
 */
export interface TeacherTaskDetailsResponse {
  taskId?: string;
  topicId?: string;
  topicName?: string;
  taskName?: string;
  description?: string;
  difficultyLevel?: number;
  publicationStatus?: PublicationStatus;
  createdAt?: string;
  updatedAt?: string;
  createdById?: string;
  /** Эталонный запрос в деталях задания. */
  sqlQuery?: TeacherTaskSqlQueryResponse;
  /** Учебная база в деталях задания. */
  targetDb?: TeacherTaskTargetDbResponse;
  attemptsCount?: number;
  lastAttempts?: TeacherTaskAttemptResponse[];
}
