/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Эталонный запрос в деталях задания.
 */
export interface TeacherTaskSqlQueryResponse {
  sqlQueryId?: string;
  sqlText?: string;
  isRequiredColumnOrder?: boolean;
  isRequiredRowOrder?: boolean;
}
