/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Данные темы тренажёра.
 */
export interface TopicResponse {
  /** Уникальный идентификатор темы. */
  id?: string;
  /** Название темы. */
  topicName?: string;
  /**
     * Идентификатор родительской темы (`null` — корневая тема).
     * @nullable
     */
  parentTopicId?: string | null;
  /** Идентификатор пользователя, создавшего запись. */
  createdById?: string;
  /** Дата и время создания (UTC). */
  createdAt?: string;
  /** Идентификатор пользователя, последним изменившего запись. */
  updatedById?: string;
  /** Дата и время последнего изменения (UTC). */
  updatedAt?: string;
}
