/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление определения параметра физического типа данных.
 */
export interface UpdateParameterDefinitionRequest {
  /** Новый ключ параметра (не более 100 символов). */
  parameterKey?: string;
  /** Новое отображаемое название параметра (не более 200 символов). */
  displayName?: string;
  /** Новый тип поля ввода (не более 50 символов). */
  inputType?: string;
  /**
     * Новое значение по умолчанию (не более 500 символов).
     * @nullable
     */
  defaultValue?: string | null;
  /** Новый порядок отображения (≥ 0). */
  sortOrder?: number;
  /** Новый шаблон SQL-фрагмента (не более 200 символов). */
  sqlFragment?: string;
  /** Новый признак обязательности параметра. */
  isRequired?: boolean;
  /**
     * Новый префикс значения (не более 50 символов).
     * @nullable
     */
  valuePrefix?: string | null;
  /**
     * Новый суффикс значения (не более 50 символов).
     * @nullable
     */
  valueSuffix?: string | null;
  /**
     * Новый разделитель (не более 10 символов).
     * @nullable
     */
  separator?: string | null;
}
