/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Полное новое состояние эталонного решения текущего задания.
 */
export interface UpdateTaskReferenceQueryRequest {
  /**
     * Учебная база для выполнения эталона.
     * @nullable
     */
  targetDbId?: string | null;
  /**
     * Текст эталонного SQL-запроса.
     * @nullable
     */
  queryText?: string | null;
  /**
     * Требовать совпадение порядка колонок.
     * @nullable
     */
  strictColumnOrder?: boolean | null;
  /**
     * Требовать совпадение порядка строк.
     * @nullable
     */
  strictRowOrder?: boolean | null;
}
