/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление физического типа данных.
 */
export interface UpdatePhysicalTypeRequest {
  /** Новое название физического типа данных (не более 100 символов). */
  typeName?: string;
}
