/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление значения параметра атрибута.
 */
export interface UpdateAttributeParameterValueRequest {
  /** Новое значение параметра (не более 500 символов). */
  parameterValue?: string;
}
