/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление эталонного SQL-запроса.
 */
export interface UpdateSqlQueryRequest {
  /** Новый текст SQL-запроса (не пустой). */
  queryText?: string;
  /** Если `true` — порядок колонок в ответе обязателен. */
  strictColumnOrder?: boolean;
  /** Если `true` — порядок строк в ответе обязателен. */
  strictRowOrder?: boolean;
}
