/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { UpdateSqlTaskRequestPublicationStatus } from './updateSqlTaskRequestPublicationStatus';

/**
 * Запрос на обновление SQL-задания.
 */
export interface UpdateSqlTaskRequest {
  /**
     * Новое название задания (не пустое, не более 300 символов).
     * @nullable
     */
  taskName?: string | null;
  /**
     * Новый текст условия задания (не пустое).
     * @nullable
     */
  taskText?: string | null;
  /**
     * Новый уровень сложности (1–5).
     * @nullable
     */
  difficultyLevel?: number | null;
  /** Новый статус публикации; null сохраняет текущий статус. */
  publicationStatus?: UpdateSqlTaskRequestPublicationStatus;
  /**
     * Новая тема; null сохраняет текущую. Смена доступна только для Draft без попыток.
     * @nullable
     */
  topicId?: string | null;
}
