/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Новый статус публикации; null сохраняет текущий статус.
 */
export type UpdateSqlTaskRequestPublicationStatus = typeof UpdateSqlTaskRequestPublicationStatus[keyof typeof UpdateSqlTaskRequestPublicationStatus];


export const UpdateSqlTaskRequestPublicationStatus = {
  Draft: 'Draft',
  Published: 'Published',
  Archived: 'Archived',
} as const;
