/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление значения ячейки (EAV).
 */
export interface UpdateCellValueRequest {
  /**
     * Новое текстовое значение ячейки (null — сброс; до 2000 символов).
     * @nullable
     */
  textValue?: string | null;
}
