/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление связи между мета-атрибутами. FK-колонки не изменяются.
 */
export interface UpdateMetaRelationshipRequest {
  /** Новое название связи. Обязательно, до 200 символов. */
  relationshipName?: string;
  /**
     * Правило при удалении. До 50 символов.
     * @nullable
     */
  deleteRule?: string | null;
  /**
     * Правило при обновлении. До 50 символов.
     * @nullable
     */
  updateRule?: string | null;
}
