/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление строки данных.
 */
export interface UpdateDataRecordRequest {
  /**
     * Новый порядок отображения строки (≥ 0). Передайте null для сброса.
     * @nullable
     */
  sortOrder?: number | null;
}
