/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { UpdateTaskReferenceTargetDbResponse } from './updateTaskReferenceTargetDbResponse';

/**
 * Актуальное состояние эталонного решения после обновления.
 */
export interface UpdateTaskReferenceQueryResponse {
  /** Сохранённый текст эталонного SQL-запроса. */
  sqlText?: string;
  /** Требуется ли совпадение порядка колонок. */
  isRequiredColumnOrder?: boolean;
  /** Требуется ли совпадение порядка строк. */
  isRequiredRowOrder?: boolean;
  /** Учебная база, в которой проверен эталон. */
  targetDb?: UpdateTaskReferenceTargetDbResponse;
}
