/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { PublicationStatus } from './publicationStatus';

/**
 * Запрос на обновление SQL-задания.
 */
export interface UpdateSqlTaskRequest {
  /** Новое название задания (не пустое, не более 300 символов). */
  taskName?: string;
  /** Новый текст условия задания (не пустое). */
  taskText?: string;
  /** Новый уровень сложности (1–5). */
  difficultyLevel?: number;
  /** Новый статус публикации; null сохраняет текущий статус. */
  publicationStatus?: PublicationStatus | null;
  /**
     * Новая тема; null сохраняет текущую. Смена доступна только для Draft без попыток.
     * @nullable
     */
  topicId?: string | null;
  /**
     * Новый эталонный запрос; null сохраняет текущий. Смена доступна только для Draft без попыток.
     * @nullable
     */
  sqlQueryId?: string | null;
}
