/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление SQL-задания (FK не меняются).
 */
export interface UpdateSqlTaskRequest {
  /** Новое название задания (не пустое, не более 300 символов). */
  taskName?: string;
  /** Новый текст условия задания (не пустое). */
  taskText?: string;
  /** Новый уровень сложности (1–5). */
  difficultyLevel?: number;
}
