/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление мета-атрибута (колонки) таблицы.
 */
export interface UpdateMetaAttributeRequest {
  /** Новое название колонки (не более 200 символов). */
  attributeName?: string;
  /** Признак первичного ключа. */
  isPrimaryKey?: boolean;
  /** Признак обязательности значения. */
  isRequired?: boolean;
  /** Порядок отображения колонки (≥ 0). */
  sortOrder?: number;
}
