/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Учебная база обновлённого эталонного решения.
 */
export interface UpdateTaskReferenceTargetDbResponse {
  /** Идентификатор учебной базы. */
  targetDbId?: string;
  /** Название учебной базы. */
  dbName?: string;
  /** Название СУБД. */
  dbmsName?: string;
}
