/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export interface UpdateDbmsDictionaryRequest {
  dbmsName?: string;
  dbmsSystemName?: string;
  dockerImage?: string;
  defaultPort?: number;
  envUserKey?: string;
  envPasswordKey?: string;
  envDatabaseKey?: string;
  /** @nullable */
  extraEnvConfig?: string | null;
  defaultDatabase?: string;
  defaultUsername?: string;
  defaultPassword?: string;
}
