/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление мета-таблицы.
 */
export interface UpdateMetaTableRequest {
  /** Новое название таблицы (не пустое, максимум 200 символов). */
  tableName?: string;
  /**
     * Новое описание таблицы (необязательно, максимум 1000 символов).
     * @nullable
     */
  description?: string | null;
}
