/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление названия темы.
 */
export interface UpdateTopicRequest {
  /** Новое название темы (не пустое, не более 300 символов). */
  topicName?: string;
}
