/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на обновление целевой БД-песочницы.
 */
export interface UpdateTargetDbRequest {
  /** Новое имя БД-песочницы. */
  dbName?: string;
  /**
     * Новое описание (передайте `null`, чтобы очистить).
     * @nullable
     */
  description?: string | null;
  /** Флаг доступа только на чтение. */
  isReadOnly?: boolean;
}
