/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Доверенный контекст платформенной сессии, отправляемый Education.
 */
export interface UpsertModuleSessionRequest {
  /**
     * Идентификатор сессии Education.
     * @nullable
     */
  sessionId?: string | null;
  /**
     * Секрет сессии для Kafka-событий и отправки оценки.
     * @nullable
     */
  sessionKey?: string | null;
  /**
     * Идентификатор студента.
     * @nullable
     */
  userId?: string | null;
  /**
     * Непрозрачная ссылка на задание; для SQL-модуля это SqlTask.Id.
     * @nullable
     */
  taskRef?: string | null;
  /**
     * Канонический адрес возврата в платформу.
     * @nullable
     */
  returnUrl?: string | null;
  /**
     * Необязательное время окончания сессии.
     * @nullable
     */
  expiresAt?: string | null;
}
