/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type ValidationViolationResponseSeverity = typeof ValidationViolationResponseSeverity[keyof typeof ValidationViolationResponseSeverity];


export const ValidationViolationResponseSeverity = {
  Error: 'Error',
  Warning: 'Warning',
} as const;
