/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type ValidationCheckPreviewResponseStatus = typeof ValidationCheckPreviewResponseStatus[keyof typeof ValidationCheckPreviewResponseStatus];


export const ValidationCheckPreviewResponseStatus = {
  Passed: 'Passed',
  Failed: 'Failed',
  NotEvaluated: 'NotEvaluated',
} as const;
