/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ValidationCheckResponseKind } from './validationCheckResponseKind';

/**
 * Сохранённый критерий проверки.
 */
export interface ValidationCheckResponse {
  id: string;
  kind: ValidationCheckResponseKind;
  /** @nullable */
  value: string | null;
  /** @nullable */
  valueDisplayName: string | null;
  weight: number;
  order: number;
}
