/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ValidationViolationResponseSeverity } from './validationViolationResponseSeverity';

/**
 * Безопасное нарушение конфигурации или эталонного решения.
 */
export interface ValidationViolationResponse {
  path: string;
  code: string;
  severity: ValidationViolationResponseSeverity;
  message: string;
}
