/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Результат успешной проверки эталонного SQL без сохранения.
 */
export interface ValidateSqlQueryResponse {
  /** Признак успешного выполнения запроса. */
  isValid?: boolean;
  /** Обнаруженные колонки результата. */
  columns?: string[];
  /** Строки preview, ограниченные настройкой Sandbox:MaxRows. */
  sampleRows?: string[][];
  /** Количество строк, возвращённых в preview. */
  rowCount?: number;
  /** Продолжительность выполнения SQL-запроса. */
  executionTimeMs?: number;
  /** Момент завершения проверки. */
  validatedAt?: string;
}
