/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import type { ValidationCheckPreviewRequestKind } from './validationCheckPreviewRequestKind';

/**
 * Критерий для preview с временным идентификатором frontend.
 */
export interface ValidationCheckPreviewRequest {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  clientKey?: string | null;
  kind?: ValidationCheckPreviewRequestKind;
  /** @nullable */
  value?: string | null;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  order?: number | null;
}
