/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

/**
 * Запрос на проверку эталонного SQL без сохранения.
 */
export interface ValidateSqlQueryRequest {
  /** Идентификатор учебной базы, на которой выполняется запрос. */
  targetDbId?: string;
  /** Проверяемый текст SQL-запроса. */
  queryText?: string;
}
