/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type ValidationViolationSeverity = typeof ValidationViolationSeverity[keyof typeof ValidationViolationSeverity];


export const ValidationViolationSeverity = {
  Error: 'Error',
  Warning: 'Warning',
} as const;
