/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */

export type ValidationCheckResponseKind = typeof ValidationCheckResponseKind[keyof typeof ValidationCheckResponseKind];


export const ValidationCheckResponseKind = {
  MainDatasetResult: 'MainDatasetResult',
  RequiredConstruct: 'RequiredConstruct',
  ForbiddenConstruct: 'ForbiddenConstruct',
  RequiredTable: 'RequiredTable',
  ForbiddenTable: 'ForbiddenTable',
} as const;
