/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HttpValidationProblemDetails,
  ProblemDetails,
  StandaloneLoginRequest,
  StandaloneLoginResponse
} from '../model';

import { sqlmoduleFetch } from '../../../shared/http/sqlmodule-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type standaloneLoginResponse200 = {
  data: StandaloneLoginResponse
  status: 200
}

export type standaloneLoginResponse401 = {
  data: ProblemDetails
  status: 401
}

export type standaloneLoginResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type standaloneLoginResponse503 = {
  data: ProblemDetails
  status: 503
}

export type standaloneLoginResponseSuccess = (standaloneLoginResponse200) & {
  headers: Headers;
};
export type standaloneLoginResponseError = (standaloneLoginResponse401 | standaloneLoginResponse422 | standaloneLoginResponse503) & {
  headers: Headers;
};

export type standaloneLoginResponse = (standaloneLoginResponseSuccess | standaloneLoginResponseError)

export const getStandaloneLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * Тонкий прокси: логинит пользователя в IdentityService и сразу обменивает полученный токен на audience SqlModule, без session_id. Секрет клиента обмена остаётся на сервере — в браузер попадает только уже готовый обменянный токен.
 * @summary Standalone-вход через SqlModule
 */
export const standaloneLogin = async (standaloneLoginRequest: StandaloneLoginRequest, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<standaloneLoginResponse> => {

  return sqlmoduleFetch<standaloneLoginResponse>(getStandaloneLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(standaloneLoginRequest)
  }
);}





export const getStandaloneLoginMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof standaloneLogin>>, TError,{data: StandaloneLoginRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof standaloneLogin>>, TError,{data: StandaloneLoginRequest}, TContext> => {

const mutationKey = ['standaloneLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof standaloneLogin>>, {data: StandaloneLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  standaloneLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type StandaloneLoginMutationResult = NonNullable<Awaited<ReturnType<typeof standaloneLogin>>>
    export type StandaloneLoginMutationBody = StandaloneLoginRequest
    export type StandaloneLoginMutationError = ProblemDetails | HttpValidationProblemDetails

    /**
 * @summary Standalone-вход через SqlModule
 */
export const useStandaloneLogin = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof standaloneLogin>>, TError,{data: StandaloneLoginRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof standaloneLogin>>,
        TError,
        {data: StandaloneLoginRequest},
        TContext
      > => {
      return useMutation(getStandaloneLoginMutationOptions(options), queryClient);
    }
