/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuditEventDtoPagedResponse,
  GetUserActivityParams,
  ListAuditEventsParams,
  ProblemDetails,
  ValidationProblemDetails
} from '../model';

import { identityFetch } from '../../../shared/http/identity-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listAuditEventsResponse200 = {
  data: AuditEventDtoPagedResponse
  status: 200
}

export type listAuditEventsResponse401 = {
  data: ProblemDetails
  status: 401
}

export type listAuditEventsResponse403 = {
  data: ProblemDetails
  status: 403
}

export type listAuditEventsResponse422 = {
  data: ValidationProblemDetails
  status: 422
}

export type listAuditEventsResponseSuccess = (listAuditEventsResponse200) & {
  headers: Headers;
};
export type listAuditEventsResponseError = (listAuditEventsResponse401 | listAuditEventsResponse403 | listAuditEventsResponse422) & {
  headers: Headers;
};

export type listAuditEventsResponse = (listAuditEventsResponseSuccess | listAuditEventsResponseError)

export const getListAuditEventsUrl = (params?: ListAuditEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/audit-events?${stringifiedParams}` : `/api/v1/audit-events`
}

/**
 * Возвращает постраничный журнал событий. Доступно только для роли Admin.
 * @summary Журнал аудита
 */
export const listAuditEvents = async (params?: ListAuditEventsParams, options?: Parameters<typeof identityFetch>[1]): Promise<listAuditEventsResponse> => {

  return identityFetch<listAuditEventsResponse>(getListAuditEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAuditEventsQueryKey = (params?: ListAuditEventsParams,) => {
    return [
    `/api/v1/audit-events`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAuditEventsQueryOptions = <TData = Awaited<ReturnType<typeof listAuditEvents>>, TError = ProblemDetails | ValidationProblemDetails>(params?: ListAuditEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditEvents>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAuditEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAuditEvents>>> = ({ signal }) => listAuditEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAuditEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAuditEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listAuditEvents>>>
export type ListAuditEventsQueryError = ProblemDetails | ValidationProblemDetails


export function useListAuditEvents<TData = Awaited<ReturnType<typeof listAuditEvents>>, TError = ProblemDetails | ValidationProblemDetails>(
 params: undefined |  ListAuditEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuditEvents>>,
          TError,
          Awaited<ReturnType<typeof listAuditEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAuditEvents<TData = Awaited<ReturnType<typeof listAuditEvents>>, TError = ProblemDetails | ValidationProblemDetails>(
 params?: ListAuditEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAuditEvents>>,
          TError,
          Awaited<ReturnType<typeof listAuditEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAuditEvents<TData = Awaited<ReturnType<typeof listAuditEvents>>, TError = ProblemDetails | ValidationProblemDetails>(
 params?: ListAuditEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditEvents>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Журнал аудита
 */

export function useListAuditEvents<TData = Awaited<ReturnType<typeof listAuditEvents>>, TError = ProblemDetails | ValidationProblemDetails>(
 params?: ListAuditEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAuditEvents>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAuditEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getUserActivityResponse200 = {
  data: AuditEventDtoPagedResponse
  status: 200
}

export type getUserActivityResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getUserActivityResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getUserActivityResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getUserActivityResponse422 = {
  data: ValidationProblemDetails
  status: 422
}

export type getUserActivityResponseSuccess = (getUserActivityResponse200) & {
  headers: Headers;
};
export type getUserActivityResponseError = (getUserActivityResponse401 | getUserActivityResponse403 | getUserActivityResponse404 | getUserActivityResponse422) & {
  headers: Headers;
};

export type getUserActivityResponse = (getUserActivityResponseSuccess | getUserActivityResponseError)

export const getGetUserActivityUrl = (id: string,
    params?: GetUserActivityParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/users/${id}/activity?${stringifiedParams}` : `/api/v1/users/${id}/activity`
}

/**
 * Возвращает события пользователя как инициатора или объекта действия. Доступно только для роли Admin.
 * @summary Активность пользователя
 */
export const getUserActivity = async (id: string,
    params?: GetUserActivityParams, options?: Parameters<typeof identityFetch>[1]): Promise<getUserActivityResponse> => {

  return identityFetch<getUserActivityResponse>(getGetUserActivityUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUserActivityQueryKey = (id: string,
    params?: GetUserActivityParams,) => {
    return [
    `/api/v1/users/${id}/activity`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUserActivityQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivity>>, TError = ProblemDetails | ValidationProblemDetails>(id: string,
    params?: GetUserActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivity>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivityQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivity>>> = ({ signal }) => getUserActivity(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserActivity>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserActivityQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivity>>>
export type GetUserActivityQueryError = ProblemDetails | ValidationProblemDetails


export function useGetUserActivity<TData = Awaited<ReturnType<typeof getUserActivity>>, TError = ProblemDetails | ValidationProblemDetails>(
 id: string,
    params: undefined |  GetUserActivityParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivity>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivity>>,
          TError,
          Awaited<ReturnType<typeof getUserActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivity<TData = Awaited<ReturnType<typeof getUserActivity>>, TError = ProblemDetails | ValidationProblemDetails>(
 id: string,
    params?: GetUserActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivity>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivity>>,
          TError,
          Awaited<ReturnType<typeof getUserActivity>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivity<TData = Awaited<ReturnType<typeof getUserActivity>>, TError = ProblemDetails | ValidationProblemDetails>(
 id: string,
    params?: GetUserActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivity>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Активность пользователя
 */

export function useGetUserActivity<TData = Awaited<ReturnType<typeof getUserActivity>>, TError = ProblemDetails | ValidationProblemDetails>(
 id: string,
    params?: GetUserActivityParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivity>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserActivityQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






