/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BatchTableRowsRequest,
  BatchTableRowsResponse,
  BatchTargetDbTableRowsHeaders,
  GetTargetDbTableLookupValuesParams,
  GetTargetDbTableRowsParams,
  HttpValidationProblemDetails,
  LookupValuesResponse,
  ProblemDetails,
  TableRowsResponse
} from '../model';

import { sqlmoduleFetch } from '../../../shared/http/sqlmodule-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getTargetDbTableRowsResponse200 = {
  data: TableRowsResponse
  status: 200
}

export type getTargetDbTableRowsResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getTargetDbTableRowsResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type getTargetDbTableRowsResponseSuccess = (getTargetDbTableRowsResponse200) & {
  headers: Headers;
};
export type getTargetDbTableRowsResponseError = (getTargetDbTableRowsResponse404 | getTargetDbTableRowsResponse422) & {
  headers: Headers;
};

export type getTargetDbTableRowsResponse = (getTargetDbTableRowsResponseSuccess | getTargetDbTableRowsResponseError)

export const getGetTargetDbTableRowsUrl = (id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/target-dbs/${id}/tables/${tableId}/rows?${stringifiedParams}` : `/api/v1/target-dbs/${id}/tables/${tableId}/rows`
}

/**
 * @summary Получить страницу учебных строк в табличном представлении
 */
export const getTargetDbTableRows = async (id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getTargetDbTableRowsResponse> => {

  return sqlmoduleFetch<getTargetDbTableRowsResponse>(getGetTargetDbTableRowsUrl(id,tableId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTargetDbTableRowsQueryKey = (id: string,
    tableId: string,
    params?: GetTargetDbTableRowsParams,) => {
    return [
    `/api/v1/target-dbs/${id}/tables/${tableId}/rows`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTargetDbTableRowsQueryOptions = <TData = Awaited<ReturnType<typeof getTargetDbTableRows>>, TError = ProblemDetails | HttpValidationProblemDetails>(id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableRows>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTargetDbTableRowsQueryKey(id,tableId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTargetDbTableRows>>> = ({ signal }) => getTargetDbTableRows(id,tableId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && tableId !== null && tableId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableRows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTargetDbTableRowsQueryResult = NonNullable<Awaited<ReturnType<typeof getTargetDbTableRows>>>
export type GetTargetDbTableRowsQueryError = ProblemDetails | HttpValidationProblemDetails


export function useGetTargetDbTableRows<TData = Awaited<ReturnType<typeof getTargetDbTableRows>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableRows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetDbTableRows>>,
          TError,
          Awaited<ReturnType<typeof getTargetDbTableRows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetDbTableRows<TData = Awaited<ReturnType<typeof getTargetDbTableRows>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableRows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetDbTableRows>>,
          TError,
          Awaited<ReturnType<typeof getTargetDbTableRows>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetDbTableRows<TData = Awaited<ReturnType<typeof getTargetDbTableRows>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableRows>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить страницу учебных строк в табличном представлении
 */

export function useGetTargetDbTableRows<TData = Awaited<ReturnType<typeof getTargetDbTableRows>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 id: string,
    tableId: string,
    params: GetTargetDbTableRowsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableRows>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTargetDbTableRowsQueryOptions(id,tableId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type batchTargetDbTableRowsResponse200 = {
  data: BatchTableRowsResponse
  status: 200
}

export type batchTargetDbTableRowsResponse404 = {
  data: ProblemDetails
  status: 404
}

export type batchTargetDbTableRowsResponse409 = {
  data: ProblemDetails
  status: 409
}

export type batchTargetDbTableRowsResponse412 = {
  data: ProblemDetails
  status: 412
}

export type batchTargetDbTableRowsResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type batchTargetDbTableRowsResponse500 = {
  data: ProblemDetails
  status: 500
}

export type batchTargetDbTableRowsResponse503 = {
  data: ProblemDetails
  status: 503
}

export type batchTargetDbTableRowsResponseSuccess = (batchTargetDbTableRowsResponse200) & {
  headers: Headers;
};
export type batchTargetDbTableRowsResponseError = (batchTargetDbTableRowsResponse404 | batchTargetDbTableRowsResponse409 | batchTargetDbTableRowsResponse412 | batchTargetDbTableRowsResponse422 | batchTargetDbTableRowsResponse500 | batchTargetDbTableRowsResponse503) & {
  headers: Headers;
};

export type batchTargetDbTableRowsResponse = (batchTargetDbTableRowsResponseSuccess | batchTargetDbTableRowsResponseError)

export const getBatchTargetDbTableRowsUrl = (id: string,
    tableId: string,) => {




  return `/api/v1/target-dbs/${id}/tables/${tableId}/rows`
}

/**
 * @summary Атомарно сохранить пакет изменений учебных строк
 */
export const batchTargetDbTableRows = async (id: string,
    tableId: string,
    batchTableRowsRequest: BatchTableRowsRequest,
    headers: BatchTargetDbTableRowsHeaders, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<batchTargetDbTableRowsResponse> => {

  return sqlmoduleFetch<batchTargetDbTableRowsResponse>(getBatchTargetDbTableRowsUrl(id,tableId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json',...headers, ...options?.headers },
    body: JSON.stringify(batchTableRowsRequest)
  }
);}





export const getBatchTargetDbTableRowsMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchTargetDbTableRows>>, TError,{id: string;tableId: string;data: BatchTableRowsRequest;headers: BatchTargetDbTableRowsHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof batchTargetDbTableRows>>, TError,{id: string;tableId: string;data: BatchTableRowsRequest;headers: BatchTargetDbTableRowsHeaders}, TContext> => {

const mutationKey = ['batchTargetDbTableRows'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchTargetDbTableRows>>, {id: string;tableId: string;data: BatchTableRowsRequest;headers: BatchTargetDbTableRowsHeaders}> = (props) => {
          const {id,tableId,data,headers} = props ?? {};

          return  batchTargetDbTableRows(id,tableId,data,headers,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type BatchTargetDbTableRowsMutationResult = NonNullable<Awaited<ReturnType<typeof batchTargetDbTableRows>>>
    export type BatchTargetDbTableRowsMutationBody = BatchTableRowsRequest
    export type BatchTargetDbTableRowsMutationError = ProblemDetails | HttpValidationProblemDetails

    /**
 * @summary Атомарно сохранить пакет изменений учебных строк
 */
export const useBatchTargetDbTableRows = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchTargetDbTableRows>>, TError,{id: string;tableId: string;data: BatchTableRowsRequest;headers: BatchTargetDbTableRowsHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchTargetDbTableRows>>,
        TError,
        {id: string;tableId: string;data: BatchTableRowsRequest;headers: BatchTargetDbTableRowsHeaders},
        TContext
      > => {
      return useMutation(getBatchTargetDbTableRowsMutationOptions(options), queryClient);
    }
    export type getTargetDbTableLookupValuesResponse200 = {
  data: LookupValuesResponse
  status: 200
}

export type getTargetDbTableLookupValuesResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getTargetDbTableLookupValuesResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getTargetDbTableLookupValuesResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getTargetDbTableLookupValuesResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type getTargetDbTableLookupValuesResponseSuccess = (getTargetDbTableLookupValuesResponse200) & {
  headers: Headers;
};
export type getTargetDbTableLookupValuesResponseError = (getTargetDbTableLookupValuesResponse401 | getTargetDbTableLookupValuesResponse403 | getTargetDbTableLookupValuesResponse404 | getTargetDbTableLookupValuesResponse422) & {
  headers: Headers;
};

export type getTargetDbTableLookupValuesResponse = (getTargetDbTableLookupValuesResponseSuccess | getTargetDbTableLookupValuesResponseError)

export const getGetTargetDbTableLookupValuesUrl = (targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/target-dbs/${targetDbId}/tables/${tableId}/lookup-values?${stringifiedParams}` : `/api/v1/target-dbs/${targetDbId}/tables/${tableId}/lookup-values`
}

/**
 * @summary Получить страницу значений связанной таблицы
 */
export const getTargetDbTableLookupValues = async (targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getTargetDbTableLookupValuesResponse> => {

  return sqlmoduleFetch<getTargetDbTableLookupValuesResponse>(getGetTargetDbTableLookupValuesUrl(targetDbId,tableId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTargetDbTableLookupValuesQueryKey = (targetDbId: string,
    tableId: string,
    params?: GetTargetDbTableLookupValuesParams,) => {
    return [
    `/api/v1/target-dbs/${targetDbId}/tables/${tableId}/lookup-values`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTargetDbTableLookupValuesQueryOptions = <TData = Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError = ProblemDetails | HttpValidationProblemDetails>(targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTargetDbTableLookupValuesQueryKey(targetDbId,tableId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>> = ({ signal }) => getTargetDbTableLookupValues(targetDbId,tableId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: targetDbId !== null && targetDbId !== undefined && tableId !== null && tableId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTargetDbTableLookupValuesQueryResult = NonNullable<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>>
export type GetTargetDbTableLookupValuesQueryError = ProblemDetails | HttpValidationProblemDetails


export function useGetTargetDbTableLookupValues<TData = Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetDbTableLookupValues>>,
          TError,
          Awaited<ReturnType<typeof getTargetDbTableLookupValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetDbTableLookupValues<TData = Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTargetDbTableLookupValues>>,
          TError,
          Awaited<ReturnType<typeof getTargetDbTableLookupValues>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTargetDbTableLookupValues<TData = Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить страницу значений связанной таблицы
 */

export function useGetTargetDbTableLookupValues<TData = Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError = ProblemDetails | HttpValidationProblemDetails>(
 targetDbId: string,
    tableId: string,
    params: GetTargetDbTableLookupValuesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTargetDbTableLookupValues>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTargetDbTableLookupValuesQueryOptions(targetDbId,tableId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






