/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { identityFetch } from '../../../shared/http/identity-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type jwksResponse200 = {
  data: unknown
  status: 200
}

export type jwksResponseSuccess = (jwksResponse200) & {
  headers: Headers;
};
;

export type jwksResponse = (jwksResponseSuccess)

export const getJwksUrl = () => {




  return `/.well-known/jwks.json`
}

/**
 * Возвращает открытый RSA-ключ для проверки подписи JWT. Issuer должен совпадать с Authority клиентского сервиса.
 * @summary Набор открытых ключей JWKS
 */
export const jwks = async ( options?: RequestInit): Promise<jwksResponse> => {

  return identityFetch<jwksResponse>(getJwksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getJwksQueryKey = () => {
    return [
    `/.well-known/jwks.json`
    ] as const;
    }


export const getJwksQueryOptions = <TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJwksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof jwks>>> = ({ signal }) => jwks({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JwksQueryResult = NonNullable<Awaited<ReturnType<typeof jwks>>>
export type JwksQueryError = unknown


export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jwks>>,
          TError,
          Awaited<ReturnType<typeof jwks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jwks>>,
          TError,
          Awaited<ReturnType<typeof jwks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Набор открытых ключей JWKS
 */

export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJwksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type openIdConfigurationResponse200 = {
  data: unknown
  status: 200
}

export type openIdConfigurationResponseSuccess = (openIdConfigurationResponse200) & {
  headers: Headers;
};
;

export type openIdConfigurationResponse = (openIdConfigurationResponseSuccess)

export const getOpenIdConfigurationUrl = () => {




  return `/.well-known/openid-configuration`
}

/**
 * Возвращает метаданные OIDC. В сервисах-клиентах Authority должен совпадать с issuer.
 * @summary Конфигурация OpenID Connect
 */
export const openIdConfiguration = async ( options?: RequestInit): Promise<openIdConfigurationResponse> => {

  return identityFetch<openIdConfigurationResponse>(getOpenIdConfigurationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getOpenIdConfigurationQueryKey = () => {
    return [
    `/.well-known/openid-configuration`
    ] as const;
    }


export const getOpenIdConfigurationQueryOptions = <TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOpenIdConfigurationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof openIdConfiguration>>> = ({ signal }) => openIdConfiguration({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OpenIdConfigurationQueryResult = NonNullable<Awaited<ReturnType<typeof openIdConfiguration>>>
export type OpenIdConfigurationQueryError = unknown


export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof openIdConfiguration>>,
          TError,
          Awaited<ReturnType<typeof openIdConfiguration>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof openIdConfiguration>>,
          TError,
          Awaited<ReturnType<typeof openIdConfiguration>>
        > , 'initialData'
      >, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Конфигурация OpenID Connect
 */

export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>>, request?: SecondParameter<typeof identityFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOpenIdConfigurationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






