/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type jwksResponse200 = {
  data: unknown
  status: 200
}

export type jwksResponseSuccess = (jwksResponse200) & {
  headers: Headers;
};
;

export type jwksResponse = (jwksResponseSuccess)

export const getJwksUrl = () => {




  return `/.well-known/jwks.json`
}

/**
 * Returns the public RSA key used to verify JWT signatures. Issuer must match Authority configured in client services.
 * @summary JSON Web Key Set
 */
export const jwks = async ( options?: RequestInit): Promise<jwksResponse> => {

  const res = await fetch(getJwksUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: jwksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as jwksResponse
}





export const getJwksQueryKey = () => {
    return [
    `/.well-known/jwks.json`
    ] as const;
    }


export const getJwksQueryOptions = <TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJwksQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof jwks>>> = ({ signal }) => jwks({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JwksQueryResult = NonNullable<Awaited<ReturnType<typeof jwks>>>
export type JwksQueryError = unknown


export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jwks>>,
          TError,
          Awaited<ReturnType<typeof jwks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jwks>>,
          TError,
          Awaited<ReturnType<typeof jwks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary JSON Web Key Set
 */

export function useJwks<TData = Awaited<ReturnType<typeof jwks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof jwks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJwksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type openIdConfigurationResponse200 = {
  data: unknown
  status: 200
}

export type openIdConfigurationResponseSuccess = (openIdConfigurationResponse200) & {
  headers: Headers;
};
;

export type openIdConfigurationResponse = (openIdConfigurationResponseSuccess)

export const getOpenIdConfigurationUrl = () => {




  return `/.well-known/openid-configuration`
}

/**
 * Minimal OIDC discovery document. Set Authority = Issuer in client JwtBearer options.
 * @summary OpenID Connect discovery document
 */
export const openIdConfiguration = async ( options?: RequestInit): Promise<openIdConfigurationResponse> => {

  const res = await fetch(getOpenIdConfigurationUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: openIdConfigurationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as openIdConfigurationResponse
}





export const getOpenIdConfigurationQueryKey = () => {
    return [
    `/.well-known/openid-configuration`
    ] as const;
    }


export const getOpenIdConfigurationQueryOptions = <TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOpenIdConfigurationQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof openIdConfiguration>>> = ({ signal }) => openIdConfiguration({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OpenIdConfigurationQueryResult = NonNullable<Awaited<ReturnType<typeof openIdConfiguration>>>
export type OpenIdConfigurationQueryError = unknown


export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof openIdConfiguration>>,
          TError,
          Awaited<ReturnType<typeof openIdConfiguration>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof openIdConfiguration>>,
          TError,
          Awaited<ReturnType<typeof openIdConfiguration>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary OpenID Connect discovery document
 */

export function useOpenIdConfiguration<TData = Awaited<ReturnType<typeof openIdConfiguration>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof openIdConfiguration>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOpenIdConfigurationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






