/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Запрос на присвоение роли пользователю (только для Admin).
 */
export interface AssignRoleRequest {
  role?: string;
}
