/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import type { AuditEventDto } from './auditEventDto';

/**
 * Постраничный ответ API.
 */
export interface AuditEventDtoPagedResponse {
  items: AuditEventDto[];
  page: number;
  pageSize: number;
  totalCount: number;
}
