/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Причина административной блокировки пользователя.
 */
export interface BlockUserRequest {
  /** @nullable */
  reason?: string | null;
}
