/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import type { UserRole } from './userRole';

/**
 * Запрос администратора на создание пользователя.
 */
export interface CreateUserRequest {
  email: string;
  /** @nullable */
  displayName?: string | null;
  password: string;
  roles: UserRole[];
}
