/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

export * from './assignRoleRequest';
export * from './loginRequest';
export * from './problemDetails';
export * from './refreshRequest';
export * from './registerRequest';
export * from './tokenResponse';
