/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Ответ с парой JWT/refresh токенов и данными аутентифицированного пользователя.
 */
export interface TokenResponse {
  accessToken: string;
  accessExpiresAt: string;
  refreshToken: string;
  refreshExpiresAt: string;
  userId: string;
  email: string;
  roles: string[];
}
