/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import type { UserRole } from './userRole';

/**
 * Запрос на атомарную замену полного набора ролей пользователя.
 */
export interface UpdateUserRolesRequest {
  roles: UserRole[];
}
