/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Пользователь в административном списке.
 */
export interface UserListItemDto {
  id: string;
  email: string;
  /** @nullable */
  displayName?: string | null;
  roles: string[];
  status: string;
  createdAt: string;
  /** @nullable */
  lastLoginAt?: string | null;
}
