/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import type { UserListItemDto } from './userListItemDto';

/**
 * Постраничный ответ API.
 */
export interface UserListItemDtoPagedResponse {
  items: UserListItemDto[];
  page: number;
  pageSize: number;
  totalCount: number;
}
