/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */

/**
 * Карточка пользователя для административного контура.
 */
export interface UserDetailsDto {
  id: string;
  email: string;
  /** @nullable */
  displayName?: string | null;
  roles: string[];
  status: string;
  createdAt: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  lastLoginAt?: string | null;
  /** @nullable */
  blockedAt?: string | null;
  /** @nullable */
  blockReason?: string | null;
}
