/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import type { ValidationProblemDetailsErrors } from './validationProblemDetailsErrors';

/**
 * Единый ответ API с ошибками валидации полей.
 */
export interface ValidationProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  errors: ValidationProblemDetailsErrors;
}
