/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HttpValidationProblemDetails,
  ProblemDetails,
  PublishTaskValidationHeaders,
  PublishTaskValidationRequest,
  TaskValidationConfigurationRequest,
  TaskValidationConfigurationResponse,
  TaskValidationPreviewRequest,
  TaskValidationPreviewResponse
} from '../model';

import { sqlmoduleFetch } from '../../../shared/http/sqlmodule-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type updateTaskValidationResponse200 = {
  data: TaskValidationConfigurationResponse
  status: 200
}

export type updateTaskValidationResponse401 = {
  data: ProblemDetails
  status: 401
}

export type updateTaskValidationResponse403 = {
  data: ProblemDetails
  status: 403
}

export type updateTaskValidationResponse404 = {
  data: ProblemDetails
  status: 404
}

export type updateTaskValidationResponse409 = {
  data: ProblemDetails
  status: 409
}

export type updateTaskValidationResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type updateTaskValidationResponse500 = {
  data: ProblemDetails
  status: 500
}

export type updateTaskValidationResponse503 = {
  data: ProblemDetails
  status: 503
}

export type updateTaskValidationResponseSuccess = (updateTaskValidationResponse200) & {
  headers: Headers;
};
export type updateTaskValidationResponseError = (updateTaskValidationResponse401 | updateTaskValidationResponse403 | updateTaskValidationResponse404 | updateTaskValidationResponse409 | updateTaskValidationResponse422 | updateTaskValidationResponse500 | updateTaskValidationResponse503) & {
  headers: Headers;
};

export type updateTaskValidationResponse = (updateTaskValidationResponseSuccess | updateTaskValidationResponseError)

export const getUpdateTaskValidationUrl = (taskId: string,) => {




  return `/api/v1/sql-tasks/${taskId}/validation`
}

export const updateTaskValidation = async (taskId: string,
    taskValidationConfigurationRequest: TaskValidationConfigurationRequest, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<updateTaskValidationResponse> => {

  return sqlmoduleFetch<updateTaskValidationResponse>(getUpdateTaskValidationUrl(taskId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(taskValidationConfigurationRequest)
  }
);}





export const getUpdateTaskValidationMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskValidation>>, TError,{taskId: string;data: TaskValidationConfigurationRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTaskValidation>>, TError,{taskId: string;data: TaskValidationConfigurationRequest}, TContext> => {

const mutationKey = ['updateTaskValidation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTaskValidation>>, {taskId: string;data: TaskValidationConfigurationRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  updateTaskValidation(taskId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTaskValidationMutationResult = NonNullable<Awaited<ReturnType<typeof updateTaskValidation>>>
    export type UpdateTaskValidationMutationBody = TaskValidationConfigurationRequest
    export type UpdateTaskValidationMutationError = ProblemDetails | HttpValidationProblemDetails

    export const useUpdateTaskValidation = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTaskValidation>>, TError,{taskId: string;data: TaskValidationConfigurationRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTaskValidation>>,
        TError,
        {taskId: string;data: TaskValidationConfigurationRequest},
        TContext
      > => {
      return useMutation(getUpdateTaskValidationMutationOptions(options), queryClient);
    }
    export type getTaskValidationResponse200 = {
  data: TaskValidationConfigurationResponse
  status: 200
}

export type getTaskValidationResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getTaskValidationResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getTaskValidationResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getTaskValidationResponse500 = {
  data: ProblemDetails
  status: 500
}

export type getTaskValidationResponseSuccess = (getTaskValidationResponse200) & {
  headers: Headers;
};
export type getTaskValidationResponseError = (getTaskValidationResponse401 | getTaskValidationResponse403 | getTaskValidationResponse404 | getTaskValidationResponse500) & {
  headers: Headers;
};

export type getTaskValidationResponse = (getTaskValidationResponseSuccess | getTaskValidationResponseError)

export const getGetTaskValidationUrl = (taskId: string,) => {




  return `/api/v1/sql-tasks/${taskId}/validation`
}

export const getTaskValidation = async (taskId: string, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getTaskValidationResponse> => {

  return sqlmoduleFetch<getTaskValidationResponse>(getGetTaskValidationUrl(taskId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTaskValidationQueryKey = (taskId: string,) => {
    return [
    `/api/v1/sql-tasks/${taskId}/validation`
    ] as const;
    }


export const getGetTaskValidationQueryOptions = <TData = Awaited<ReturnType<typeof getTaskValidation>>, TError = ProblemDetails>(taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskValidation>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaskValidationQueryKey(taskId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaskValidation>>> = ({ signal }) => getTaskValidation(taskId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: taskId !== null && taskId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaskValidation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaskValidationQueryResult = NonNullable<Awaited<ReturnType<typeof getTaskValidation>>>
export type GetTaskValidationQueryError = ProblemDetails


export function useGetTaskValidation<TData = Awaited<ReturnType<typeof getTaskValidation>>, TError = ProblemDetails>(
 taskId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskValidation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskValidation>>,
          TError,
          Awaited<ReturnType<typeof getTaskValidation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskValidation<TData = Awaited<ReturnType<typeof getTaskValidation>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskValidation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaskValidation>>,
          TError,
          Awaited<ReturnType<typeof getTaskValidation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaskValidation<TData = Awaited<ReturnType<typeof getTaskValidation>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskValidation>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTaskValidation<TData = Awaited<ReturnType<typeof getTaskValidation>>, TError = ProblemDetails>(
 taskId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaskValidation>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaskValidationQueryOptions(taskId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type publishTaskValidationResponse200 = {
  data: TaskValidationConfigurationResponse
  status: 200
}

export type publishTaskValidationResponse401 = {
  data: ProblemDetails
  status: 401
}

export type publishTaskValidationResponse403 = {
  data: ProblemDetails
  status: 403
}

export type publishTaskValidationResponse404 = {
  data: ProblemDetails
  status: 404
}

export type publishTaskValidationResponse409 = {
  data: ProblemDetails
  status: 409
}

export type publishTaskValidationResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type publishTaskValidationResponse500 = {
  data: ProblemDetails
  status: 500
}

export type publishTaskValidationResponse503 = {
  data: ProblemDetails
  status: 503
}

export type publishTaskValidationResponseSuccess = (publishTaskValidationResponse200) & {
  headers: Headers;
};
export type publishTaskValidationResponseError = (publishTaskValidationResponse401 | publishTaskValidationResponse403 | publishTaskValidationResponse404 | publishTaskValidationResponse409 | publishTaskValidationResponse422 | publishTaskValidationResponse500 | publishTaskValidationResponse503) & {
  headers: Headers;
};

export type publishTaskValidationResponse = (publishTaskValidationResponseSuccess | publishTaskValidationResponseError)

export const getPublishTaskValidationUrl = (taskId: string,) => {




  return `/api/v1/sql-tasks/${taskId}/validation/publish`
}

export const publishTaskValidation = async (taskId: string,
    publishTaskValidationRequest: PublishTaskValidationRequest,
    headers: PublishTaskValidationHeaders, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<publishTaskValidationResponse> => {

  return sqlmoduleFetch<publishTaskValidationResponse>(getPublishTaskValidationUrl(taskId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json',...headers, ...options?.headers },
    body: JSON.stringify(publishTaskValidationRequest)
  }
);}





export const getPublishTaskValidationMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishTaskValidation>>, TError,{taskId: string;data: PublishTaskValidationRequest;headers: PublishTaskValidationHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof publishTaskValidation>>, TError,{taskId: string;data: PublishTaskValidationRequest;headers: PublishTaskValidationHeaders}, TContext> => {

const mutationKey = ['publishTaskValidation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishTaskValidation>>, {taskId: string;data: PublishTaskValidationRequest;headers: PublishTaskValidationHeaders}> = (props) => {
          const {taskId,data,headers} = props ?? {};

          return  publishTaskValidation(taskId,data,headers,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PublishTaskValidationMutationResult = NonNullable<Awaited<ReturnType<typeof publishTaskValidation>>>
    export type PublishTaskValidationMutationBody = PublishTaskValidationRequest
    export type PublishTaskValidationMutationError = ProblemDetails | HttpValidationProblemDetails

    export const usePublishTaskValidation = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishTaskValidation>>, TError,{taskId: string;data: PublishTaskValidationRequest;headers: PublishTaskValidationHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishTaskValidation>>,
        TError,
        {taskId: string;data: PublishTaskValidationRequest;headers: PublishTaskValidationHeaders},
        TContext
      > => {
      return useMutation(getPublishTaskValidationMutationOptions(options), queryClient);
    }
    export type previewTaskValidationResponse200 = {
  data: TaskValidationPreviewResponse
  status: 200
}

export type previewTaskValidationResponse401 = {
  data: ProblemDetails
  status: 401
}

export type previewTaskValidationResponse403 = {
  data: ProblemDetails
  status: 403
}

export type previewTaskValidationResponse404 = {
  data: ProblemDetails
  status: 404
}

export type previewTaskValidationResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type previewTaskValidationResponse500 = {
  data: ProblemDetails
  status: 500
}

export type previewTaskValidationResponse503 = {
  data: ProblemDetails
  status: 503
}

export type previewTaskValidationResponseSuccess = (previewTaskValidationResponse200) & {
  headers: Headers;
};
export type previewTaskValidationResponseError = (previewTaskValidationResponse401 | previewTaskValidationResponse403 | previewTaskValidationResponse404 | previewTaskValidationResponse422 | previewTaskValidationResponse500 | previewTaskValidationResponse503) & {
  headers: Headers;
};

export type previewTaskValidationResponse = (previewTaskValidationResponseSuccess | previewTaskValidationResponseError)

export const getPreviewTaskValidationUrl = (taskId: string,) => {




  return `/api/v1/sql-tasks/${taskId}/validation/preview`
}

export const previewTaskValidation = async (taskId: string,
    taskValidationPreviewRequest: TaskValidationPreviewRequest, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<previewTaskValidationResponse> => {

  return sqlmoduleFetch<previewTaskValidationResponse>(getPreviewTaskValidationUrl(taskId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(taskValidationPreviewRequest)
  }
);}





export const getPreviewTaskValidationMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewTaskValidation>>, TError,{taskId: string;data: TaskValidationPreviewRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof previewTaskValidation>>, TError,{taskId: string;data: TaskValidationPreviewRequest}, TContext> => {

const mutationKey = ['previewTaskValidation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof previewTaskValidation>>, {taskId: string;data: TaskValidationPreviewRequest}> = (props) => {
          const {taskId,data} = props ?? {};

          return  previewTaskValidation(taskId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PreviewTaskValidationMutationResult = NonNullable<Awaited<ReturnType<typeof previewTaskValidation>>>
    export type PreviewTaskValidationMutationBody = TaskValidationPreviewRequest
    export type PreviewTaskValidationMutationError = ProblemDetails | HttpValidationProblemDetails

    export const usePreviewTaskValidation = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewTaskValidation>>, TError,{taskId: string;data: TaskValidationPreviewRequest}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof previewTaskValidation>>,
        TError,
        {taskId: string;data: TaskValidationPreviewRequest},
        TContext
      > => {
      return useMutation(getPreviewTaskValidationMutationOptions(options), queryClient);
    }
