/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * IdentityService API
 * Сервис аутентификации и авторизации платформы Scoodle.
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AssignRoleRequest,
  ProblemDetails
} from '../model';





export type assignRoleResponse204 = {
  data: void
  status: 204
}

export type assignRoleResponse401 = {
  data: ProblemDetails
  status: 401
}

export type assignRoleResponse403 = {
  data: ProblemDetails
  status: 403
}

export type assignRoleResponse404 = {
  data: ProblemDetails
  status: 404
}

export type assignRoleResponse409 = {
  data: ProblemDetails
  status: 409
}

export type assignRoleResponseSuccess = (assignRoleResponse204) & {
  headers: Headers;
};
export type assignRoleResponseError = (assignRoleResponse401 | assignRoleResponse403 | assignRoleResponse404 | assignRoleResponse409) & {
  headers: Headers;
};

export type assignRoleResponse = (assignRoleResponseSuccess | assignRoleResponseError)

export const getAssignRoleUrl = (id: string,) => {




  return `/api/v1/users/${id}/roles`
}

/**
 * Только для Admin. Присваивает существующую роль указанному пользователю.
 * @summary Присвоение роли пользователю
 */
export const assignRole = async (id: string,
    assignRoleRequest: AssignRoleRequest, options?: RequestInit): Promise<assignRoleResponse> => {

  const res = await fetch(getAssignRoleUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(assignRoleRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assignRoleResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as assignRoleResponse
}





export const getAssignRoleMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRole>>, TError,{id: string;data: AssignRoleRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof assignRole>>, TError,{id: string;data: AssignRoleRequest}, TContext> => {

const mutationKey = ['assignRole'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof assignRole>>, {id: string;data: AssignRoleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  assignRole(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AssignRoleMutationResult = NonNullable<Awaited<ReturnType<typeof assignRole>>>
    export type AssignRoleMutationBody = AssignRoleRequest
    export type AssignRoleMutationError = ProblemDetails

    /**
 * @summary Присвоение роли пользователю
 */
export const useAssignRole = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof assignRole>>, TError,{id: string;data: AssignRoleRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof assignRole>>,
        TError,
        {id: string;data: AssignRoleRequest},
        TContext
      > => {
      return useMutation(getAssignRoleMutationOptions(options), queryClient);
    }
