/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * SQLModule API
 * API SQL-тренажёра (модуль Scoodle).
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CurrentModuleSessionResponse,
  FinalizeCurrentModuleSessionHeaders,
  GetModuleTasksCatalogHeaders,
  HttpValidationProblemDetails,
  ModuleTaskCatalogItemResponse,
  ProblemDetails,
  ProgressFinalizationResponse,
  UpsertModuleSessionHeaders,
  UpsertModuleSessionRequest
} from '../model';

import { sqlmoduleFetch } from '../../../shared/http/sqlmodule-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type finalizeCurrentModuleSessionResponse200 = {
  data: ProgressFinalizationResponse
  status: 200
}

export type finalizeCurrentModuleSessionResponse401 = {
  data: ProblemDetails
  status: 401
}

export type finalizeCurrentModuleSessionResponse403 = {
  data: ProblemDetails
  status: 403
}

export type finalizeCurrentModuleSessionResponse404 = {
  data: ProblemDetails
  status: 404
}

export type finalizeCurrentModuleSessionResponse409 = {
  data: ProblemDetails
  status: 409
}

export type finalizeCurrentModuleSessionResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type finalizeCurrentModuleSessionResponseSuccess = (finalizeCurrentModuleSessionResponse200) & {
  headers: Headers;
};
export type finalizeCurrentModuleSessionResponseError = (finalizeCurrentModuleSessionResponse401 | finalizeCurrentModuleSessionResponse403 | finalizeCurrentModuleSessionResponse404 | finalizeCurrentModuleSessionResponse409 | finalizeCurrentModuleSessionResponse422) & {
  headers: Headers;
};

export type finalizeCurrentModuleSessionResponse = (finalizeCurrentModuleSessionResponseSuccess | finalizeCurrentModuleSessionResponseError)

export const getFinalizeCurrentModuleSessionUrl = () => {




  return `/api/v1/module-integration/sessions/current/finalize`
}

/**
 * Фиксирует фактический BestScore и атомарно ставит один итог в outbox Education.
 * @summary Завершить текущее платформенное прохождение
 */
export const finalizeCurrentModuleSession = async (headers: FinalizeCurrentModuleSessionHeaders, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<finalizeCurrentModuleSessionResponse> => {

  return sqlmoduleFetch<finalizeCurrentModuleSessionResponse>(getFinalizeCurrentModuleSessionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { ...headers, ...options?.headers }

  }
);}





export const getFinalizeCurrentModuleSessionMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizeCurrentModuleSession>>, TError,{headers: FinalizeCurrentModuleSessionHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof finalizeCurrentModuleSession>>, TError,{headers: FinalizeCurrentModuleSessionHeaders}, TContext> => {

const mutationKey = ['finalizeCurrentModuleSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finalizeCurrentModuleSession>>, {headers: FinalizeCurrentModuleSessionHeaders}> = (props) => {
          const {headers} = props ?? {};

          return  finalizeCurrentModuleSession(headers,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type FinalizeCurrentModuleSessionMutationResult = NonNullable<Awaited<ReturnType<typeof finalizeCurrentModuleSession>>>

    export type FinalizeCurrentModuleSessionMutationError = ProblemDetails | HttpValidationProblemDetails

    /**
 * @summary Завершить текущее платформенное прохождение
 */
export const useFinalizeCurrentModuleSession = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finalizeCurrentModuleSession>>, TError,{headers: FinalizeCurrentModuleSessionHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finalizeCurrentModuleSession>>,
        TError,
        {headers: FinalizeCurrentModuleSessionHeaders},
        TContext
      > => {
      return useMutation(getFinalizeCurrentModuleSessionMutationOptions(options), queryClient);
    }
    export type getCurrentModuleSessionResponse200 = {
  data: CurrentModuleSessionResponse
  status: 200
}

export type getCurrentModuleSessionResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getCurrentModuleSessionResponse403 = {
  data: ProblemDetails
  status: 403
}

export type getCurrentModuleSessionResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getCurrentModuleSessionResponseSuccess = (getCurrentModuleSessionResponse200) & {
  headers: Headers;
};
export type getCurrentModuleSessionResponseError = (getCurrentModuleSessionResponse401 | getCurrentModuleSessionResponse403 | getCurrentModuleSessionResponse404) & {
  headers: Headers;
};

export type getCurrentModuleSessionResponse = (getCurrentModuleSessionResponseSuccess | getCurrentModuleSessionResponseError)

export const getGetCurrentModuleSessionUrl = () => {




  return `/api/v1/module-integration/sessions/current`
}

/**
 * Берёт session_id и пользователя только из валидированного JWT. Отсутствующая, неизвестная или чужая сессия скрывается единым ответом 404.
 * @summary Получить текущую платформенную сессию
 */
export const getCurrentModuleSession = async ( options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getCurrentModuleSessionResponse> => {

  return sqlmoduleFetch<getCurrentModuleSessionResponse>(getGetCurrentModuleSessionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCurrentModuleSessionQueryKey = () => {
    return [
    `/api/v1/module-integration/sessions/current`
    ] as const;
    }


export const getGetCurrentModuleSessionQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentModuleSessionQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentModuleSession>>> = ({ signal }) => getCurrentModuleSession({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentModuleSessionQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentModuleSession>>>
export type GetCurrentModuleSessionQueryError = ProblemDetails


export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentModuleSession>>,
          TError,
          Awaited<ReturnType<typeof getCurrentModuleSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentModuleSession>>,
          TError,
          Awaited<ReturnType<typeof getCurrentModuleSession>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить текущую платформенную сессию
 */

export function useGetCurrentModuleSession<TData = Awaited<ReturnType<typeof getCurrentModuleSession>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentModuleSession>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentModuleSessionQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getModuleTasksCatalogResponse200 = {
  data: ModuleTaskCatalogItemResponse[]
  status: 200
}

export type getModuleTasksCatalogResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getModuleTasksCatalogResponseSuccess = (getModuleTasksCatalogResponse200) & {
  headers: Headers;
};
export type getModuleTasksCatalogResponseError = (getModuleTasksCatalogResponse401) & {
  headers: Headers;
};

export type getModuleTasksCatalogResponse = (getModuleTasksCatalogResponseSuccess | getModuleTasksCatalogResponseError)

export const getGetModuleTasksCatalogUrl = () => {




  return `/api/v1/module-integration/tasks-catalog`
}

/**
 * Сервер-сервер каталог для Education. Требует X-Service-Key и возвращает только Published-задания.
 * @summary Получить каталог опубликованных SQL-заданий
 */
export const getModuleTasksCatalog = async (headers: GetModuleTasksCatalogHeaders, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<getModuleTasksCatalogResponse> => {

  return sqlmoduleFetch<getModuleTasksCatalogResponse>(getGetModuleTasksCatalogUrl(),
  {
    ...options,
    method: 'GET',
    headers: { ...headers, ...options?.headers }

  }
);}





export const getGetModuleTasksCatalogQueryKey = () => {
    return [
    `/api/v1/module-integration/tasks-catalog`
    ] as const;
    }


export const getGetModuleTasksCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError = ProblemDetails>(headers: GetModuleTasksCatalogHeaders, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetModuleTasksCatalogQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getModuleTasksCatalog>>> = ({ signal }) => getModuleTasksCatalog(headers, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetModuleTasksCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getModuleTasksCatalog>>>
export type GetModuleTasksCatalogQueryError = ProblemDetails


export function useGetModuleTasksCatalog<TData = Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError = ProblemDetails>(
 headers: GetModuleTasksCatalogHeaders, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleTasksCatalog>>,
          TError,
          Awaited<ReturnType<typeof getModuleTasksCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleTasksCatalog<TData = Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError = ProblemDetails>(
 headers: GetModuleTasksCatalogHeaders, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getModuleTasksCatalog>>,
          TError,
          Awaited<ReturnType<typeof getModuleTasksCatalog>>
        > , 'initialData'
      >, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetModuleTasksCatalog<TData = Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError = ProblemDetails>(
 headers: GetModuleTasksCatalogHeaders, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить каталог опубликованных SQL-заданий
 */

export function useGetModuleTasksCatalog<TData = Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError = ProblemDetails>(
 headers: GetModuleTasksCatalogHeaders, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getModuleTasksCatalog>>, TError, TData>>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetModuleTasksCatalogQueryOptions(headers,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type upsertModuleSessionResponse200 = {
  data: void
  status: 200
}

export type upsertModuleSessionResponse401 = {
  data: ProblemDetails
  status: 401
}

export type upsertModuleSessionResponse409 = {
  data: ProblemDetails
  status: 409
}

export type upsertModuleSessionResponse422 = {
  data: HttpValidationProblemDetails
  status: 422
}

export type upsertModuleSessionResponseSuccess = (upsertModuleSessionResponse200) & {
  headers: Headers;
};
export type upsertModuleSessionResponseError = (upsertModuleSessionResponse401 | upsertModuleSessionResponse409 | upsertModuleSessionResponse422) & {
  headers: Headers;
};

export type upsertModuleSessionResponse = (upsertModuleSessionResponseSuccess | upsertModuleSessionResponseError)

export const getUpsertModuleSessionUrl = () => {




  return `/api/v1/module-integration/sessions`
}

/**
 * Сервер-сервер push от Education. Повторный push синхронизирует Active-сессию; Completed-сессия отвечает 409 и не изменяется.
 * @summary Создать или восстановить платформенную сессию
 */
export const upsertModuleSession = async (upsertModuleSessionRequest: UpsertModuleSessionRequest,
    headers: UpsertModuleSessionHeaders, options?: Parameters<typeof sqlmoduleFetch>[1]): Promise<upsertModuleSessionResponse> => {

  return sqlmoduleFetch<upsertModuleSessionResponse>(getUpsertModuleSessionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json',...headers, ...options?.headers },
    body: JSON.stringify(upsertModuleSessionRequest)
  }
);}





export const getUpsertModuleSessionMutationOptions = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertModuleSession>>, TError,{data: UpsertModuleSessionRequest;headers: UpsertModuleSessionHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof upsertModuleSession>>, TError,{data: UpsertModuleSessionRequest;headers: UpsertModuleSessionHeaders}, TContext> => {

const mutationKey = ['upsertModuleSession'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof upsertModuleSession>>, {data: UpsertModuleSessionRequest;headers: UpsertModuleSessionHeaders}> = (props) => {
          const {data,headers} = props ?? {};

          return  upsertModuleSession(data,headers,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpsertModuleSessionMutationResult = NonNullable<Awaited<ReturnType<typeof upsertModuleSession>>>
    export type UpsertModuleSessionMutationBody = UpsertModuleSessionRequest
    export type UpsertModuleSessionMutationError = ProblemDetails | HttpValidationProblemDetails

    /**
 * @summary Создать или восстановить платформенную сессию
 */
export const useUpsertModuleSession = <TError = ProblemDetails | HttpValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof upsertModuleSession>>, TError,{data: UpsertModuleSessionRequest;headers: UpsertModuleSessionHeaders}, TContext>, request?: SecondParameter<typeof sqlmoduleFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof upsertModuleSession>>,
        TError,
        {data: UpsertModuleSessionRequest;headers: UpsertModuleSessionHeaders},
        TContext
      > => {
      return useMutation(getUpsertModuleSessionMutationOptions(options), queryClient);
    }
